### ISSUE TITLE
IndexOutOfBoundsException in LayoutManager during onLayoutChildren 

### ISSUE THREAD

**Issue by jj3chen** [TonicArtos/SuperSLiM#101]
View anchorView = getAnchorChild();
requestedPosition = anchorView == null ? 0 : Math.min(getPosition(anchorView), itemCount - 1), 0);
...
int bottomLine = layoutChildren(requestedPosition, borderLine, layoutState);

Problem: App crashes at the last line when getPosiiton(anchorView) returns -1 for position
Solution: If set requestedPosition to 0 when it is -1

**Comment by incandesco** [comment]
I found this happening when I had a single section with no header and tried removing the first cell (the lack of a header seems to be the key).  I am currently working around this by adding a 1 pixel high header with a transparent background - I tried a zero height header and it solved the crash but caused some positioning problems after an notifyItemRangeRemoved(...).

**Comment by wiradikusuma** [comment]
Any news on this? It's happening to me because I'm using "loading indicator". I'm using infinite scrolling, and I add/remove 1 extra view with progress bar at the bottom of the list.
