### ISSUE TITLE
feature comparision

### ISSUE THREAD

**Issue by jjhesk** [TonicArtos/SuperSLiM#107]
what is the difference compared to [ultimaterecyclerview](https://github.com/cymcsg/UltimateRecyclerView)

**Comment by TonicArtos** [comment]
This kind of question is inappropriate for a project bug tracker. Personally, I don't really care to contrast this library with others, or to suggest one is better or worse for any reason. However, here is a revised project description for SuperSLiM, perhaps you can figure out the differences from that description. 

'''
SuperSLiM provides a focused set of features centered around a logical presentation of data in a scrollable list. Specifically, it allows you to combine together different kinds of layouts in a single scrolling view. Each of these layouts is associated with a section (group of views provided by your adapter), and each section can have a header. There are various customisation options for the headers and layouts. 
'''
