### ISSUE TITLE
slm_section_headerMarginStart seems problematic when using background drawables

### ISSUE THREAD

**Issue by ThanosFisherman** [TonicArtos/SuperSLiM#109]
Hello, this is a minor bug in my opinion and I've already found a workaround. 
I'll try to explain this with pics.
first I set a background drawable to my normal list item layout like so
`android:background="@drawable/listselector"`
Now when I click the an item on the list everything works fine
![screenshot_2015-06-22-03-09-41](https://cloud.githubusercontent.com/assets/4888330/8273992/4bc306c2-188d-11e5-891d-ce45629d53a2.png)

Now here comes the problem. When I add `app:slm_section_headerMarginStart="16dp"` to my Header layout file, the background drawable is not correctly applied to the layout items when I click on them
![screenshot_2015-06-22-03-12-09](https://cloud.githubusercontent.com/assets/4888330/8274009/b4c99776-188d-11e5-8b5d-da2ce30c3556.png)

Good thing I worked this arround by removing `app:slm_section_headerMarginStart` from header layout and added a left padding to my items layout. So no big deal

**Comment by TonicArtos** [comment]
Are you saying that the background drawable is being drawn inside the header margin?

**Comment by ThanosFisherman** [comment]
Yeah I guess.
Just add any background color to normal items layout. Then go to your header layout and add something like `app:slm_section_headerMarginStart="12dp"` 
I would expect this bg color to cover the entire view but instead I get this:
![screenshot_2015-06-26-17-27-03](https://cloud.githubusercontent.com/assets/4888330/8379585/bbe35cdc-1c29-11e5-8069-cb89b8ea3717.png)
But As I said I worked this around by completely removing the `app:slm_section_headerMarginStart="12dp"` from the header and just added `android:paddingLeft="16dp"` to my normal item layout

**Comment by TonicArtos** [comment]
Okay, I guess this is a misunderstanding of the purpose of the header margin. Probably header margin should be ignored for inline headers. The prupose of the header margin is used to set the area reserved only for the header when it is aligned to the side. The content items are positioned to not be in this area, which is why the bg images and colour was not extending into the margin.

**Comment by ThanosFisherman** [comment]
Oh I see what you mean. Sorry for the misunderstanding. You can close this issue or whatever

**Comment by TonicArtos** [comment]
No problems, I am going to use this issue to track the issue until the documentation is updated to explain header margin.
