### ISSUE TITLE
Bug detected in LinearSLM

### ISSUE THREAD

**Issue by esskar** [TonicArtos/SuperSLiM#110]
https://github.com/TonicArtos/SuperSLiM/blob/early_release_4/library/src/main/java/com/tonicartos/superslim/LinearSLM.java#L73

This looks like a bug - either the loop is useless or you should put i as parameter for getChildAt.

**Comment by TonicArtos** [comment]
Ah, thanks. This was fixed in development, I didn't notice it on the release branch.

**Comment by esskar** [comment]
What's the develop branch?

**Comment by TonicArtos** [comment]
The current release branch is early_release_4. The development branch is master.
