### ISSUE TITLE
View binding not working as expected using a grid of images

### ISSUE THREAD

**Issue by alessandroRoaro** [TonicArtos/SuperSLiM#111]
I have set up a grid only layout with a sticky-inline header, with a fixed number of columns (3). The items are squared and have all the same size, and contain only an ImageView.

The issue is that onBindViewHolder is called not as expected, as the following logs that I put in the method show:

06-22 19:07:46.335  19569-19569/? D/GridAdapter﹕ binding view 0
06-22 19:07:46.335  19569-19569/? D/GridAdapter﹕ binding view 1
06-22 19:07:46.345  19569-19569/? D/GridAdapter﹕ binding view 2
06-22 19:07:46.355  19569-19569/? D/GridAdapter﹕ binding view 3
06-22 19:07:46.355  19569-19569/? D/GridAdapter﹕ binding view 4
06-22 19:07:46.355  19569-19569/? D/GridAdapter﹕ binding view 4
06-22 19:07:46.355  19569-19569/? D/GridAdapter﹕ binding view 5
06-22 19:07:46.365  19569-19569/? D/GridAdapter﹕ binding view 6
06-22 19:07:46.365  19569-19569/? D/GridAdapter﹕ binding view 7
06-22 19:07:46.375  19569-19569/? D/GridAdapter﹕ binding view 7
06-22 19:07:46.375  19569-19569/? D/GridAdapter﹕ binding view 8
06-22 19:07:46.375  19569-19569/? D/GridAdapter﹕ binding view 9
06-22 19:07:46.385  19569-19569/? D/GridAdapter﹕ binding view 10
06-22 19:07:46.385  19569-19569/? D/GridAdapter﹕ binding view 10
06-22 19:07:46.385  19569-19569/? D/GridAdapter﹕ binding view 11
06-22 19:07:46.385  19569-19569/? D/GridAdapter﹕ binding view 12
06-22 19:07:46.385  19569-19569/? D/GridAdapter﹕ binding view 13
06-22 19:07:46.395  19569-19569/? D/GridAdapter﹕ binding view 13
06-22 19:07:46.395  19569-19569/? D/GridAdapter﹕ binding view 14
06-22 19:07:46.395  19569-19569/? D/GridAdapter﹕ binding view 15
06-22 19:07:46.566  19569-19569/? D/GridAdapter﹕ binding view 4
06-22 19:07:46.566  19569-19569/? D/GridAdapter﹕ binding view 7
06-22 19:07:46.566  19569-19569/? D/GridAdapter﹕ binding view 10
06-22 19:07:46.576  19569-19569/? D/GridAdapter﹕ binding view 13
06-22 19:07:46.586  19569-19569/? D/GridAdapter﹕ binding view 15
06-22 19:07:46.626  19569-19569/? D/GridAdapter﹕ binding view 4
06-22 19:07:46.626  19569-19569/? D/GridAdapter﹕ binding view 10
06-22 19:07:46.636  19569-19569/? D/GridAdapter﹕ binding view 15
06-22 19:07:46.726  19569-19569/? D/GridAdapter﹕ binding view 4
06-22 19:07:46.726  19569-19569/? D/GridAdapter﹕ binding view 10
06-22 19:07:46.746  19569-19569/? D/GridAdapter﹕ binding view 15
06-22 19:07:46.826  19569-19569/? D/GridAdapter﹕ binding view 4
06-22 19:07:46.826  19569-19569/? D/GridAdapter﹕ binding view 10
06-22 19:07:46.836  19569-19569/? D/GridAdapter﹕ binding view 15
06-22 19:07:46.856  19569-19569/? D/GridAdapter﹕ binding view 4
06-22 19:07:46.866  19569-19569/? D/GridAdapter﹕ binding view 10
06-22 19:07:46.866  19569-19569/? D/GridAdapter﹕ binding view 15
06-22 19:07:46.926  19569-19569/? D/GridAdapter﹕ binding view 4

However, if I put the ImageView inside a FrameLayout, it works fine.

**Comment by TonicArtos** [comment]
I have been working on fixes to this in 0.5.

**Comment by peshkira** [comment]
@alessandroRoaro Hey. Were you able to resolve this? How exactly did the FrameLayout help? Were you loading the images from the web? 

I am currently having the same issue and I can't seem to find a way around it. I am using volleys NetworkImageView to load the images, which usually works great. Any feedback is much appreciated.

**Comment by alessandroRoaro** [comment]
@peshkira The images were stored locally. From what I recall, using a FrameLayout containing the ImageView, instead of putting simply the ImageView by itself in the grid, solved the issue. However there was some other issue that I don't remember, so in the end I gave it up and I'm waiting for the version 0.5 with the fix :) Btw I was using UIL to load the images (Universal Image Loader)

**Comment by peshkira** [comment]
Thanks very much for the info.

@TonicArtos Do you have a tip for what the problem might be? I'd like to take a look, if I could fix it.
