### ISSUE TITLE
Section items flashing when underlying dataset changes and notifyItemInserted() or notifyItemRemoved() is called

### ISSUE THREAD

**Issue by gergokajtar** [TonicArtos/SuperSLiM#114]
Please check this video for further explanation: http://youtu.be/q7sIufPQ-vs

Interesting thing is that the sections first item is not flashing, only from the second on it is doing it.

**Comment by TonicArtos** [comment]
Yeah, data changes are bugged, and it got worse with one of the RecyclerView updates. I am working on fixes in 0.5.

**Comment by gergokajtar** [comment]
Thanks, I will try to take a look at it, maybe I see something.

**Comment by awanishraj** [comment]
Hey guys. I am using v0.4.13 of the library.

In my recycler view, I have full width section headers and grid of images under each section.
But, notifyItemChanged(i) is triggering onBindViewHolder() on multiple positions (besides 'i'), which is causing flashing.

This seems like a similar problem. I tried looking into the library, but couldn't track it.

Is there a workaround you can suggest? Or direct me to the part of the library that might be causing this issue. Thanks.

**Comment by TonicArtos** [comment]
This is because the library doesn't properly support the individual data change notifications yet. As a result it laying out many items and the recycler view is getting confused. if with earlier versions of the recycler view it wasn't a visual problem, but a recent update caused this new behaviour.

**Comment by plackemacher** [comment]
+1 running into the same issue in our app.

**Comment by incandesco** [comment]
I found this problem today (note: I am using stable ids).  I wrote a patch version of GridSLM.java that seems to resolve it nicely in my particular case.

At roughly line 120, I replaced:
<pre>            LayoutState.View view = state.getView(i);
            if (view.getLayoutParams().getTestedFirstPosition() != sd.firstPosition) {
                state.cacheView(i, view.view);
                break;
            }
</pre>

With:

<pre>            LayoutState.View view = state.getView(i);
            state.cacheView(i, view.view);
            if (view.getLayoutParams().getTestedFirstPosition() != sd.firstPosition) {
                break;
            }
</pre>
Hi Tonic, nice library, thanks.

**Comment by DennyWeinberg** [comment]
Thanks for sharing this! It sould be merged into the v4 no? It works like a charm.
