### ISSUE TITLE
java.lang.IndexOutOfBoundsException

### ISSUE THREAD

**Issue by Geekince** [TonicArtos/SuperSLiM#116]
java.lang.IndexOutOfBoundsException: Inconsistency detected. Invalid item position 7(offset:7).state:78 at android.support.v7.widget.cs.a(RecyclerView.java:4320) at android.support.v7.widget.cs.b(RecyclerView.java:4278) atandroid.support.v7.widget.RecyclerView.a(RecyclerView.java:1355) at android.support.v7.widget.RecyclerView.onTouchEvent(RecyclerView.java:2209) at android.view.View.dispatchTouchEvent(View.java:7801) at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2335) at

**Comment by zhengzhou** [comment]
same..
