### ISSUE TITLE
RecyclerView needs to be updated to latest

### ISSUE THREAD

**Issue by ThanosFisherman** [TonicArtos/SuperSLiM#117]
Hey, Tonic could you please update your build file to latest? RecyclerView, compileSdkVersion, targetSdkVersion etc? 

I'm currently using SuperSlim 0.4.13 via gradle dependency but I'm unable to make this cooperate with `<android.support.design.widget.CoordinatorLayout>`  from android design library 22.2.1

I suspect this is because SuperSlim is using an outdated version of RecyclerView. I actually made it work by downloading the library and updating it myself but I'd rather use the library from gradle instead of having the whole module in my project

**Comment by luwei2012** [comment]
I suspect this is because there are something wrong with your code. I'm using android design library and there's no problem except smoothScrollToPosition method.

**Comment by ThanosFisherman** [comment]
@luwei2012 I'm trying to have a show/hide behaviour of toolbar when user scrolls on RecyclerView. It worked as expected when I manually downloaded the library module and Updated its build file myself.
