### ISSUE TITLE
Maven dependency?

### ISSUE THREAD

**Issue by stephanemaarek** [TonicArtos/SuperSLiM#12]
Would be nice to just include the library as a dependency.

**Comment by nitrico** [comment]
+1. But I think he will add it when the library gets closer to the final
release.

**Comment by niltoft** [comment]
+1

**Comment by stephanemaarek** [comment]
Thanks man! Can you post the right depency here or in the read me? Really
appreciate your work

**Comment by TonicArtos** [comment]
I only just uploaded it and I haven't tested using it from maven yet. Please let me know how it goes.

dependencies {
    compile 'com.tonicartos:superslim:0.1-SNAPSHOT'
}

**Comment by stephanemaarek** [comment]
Didn't work for me yet
Will retry in a few

**Comment by TonicArtos** [comment]
I published on maven central. Try adding that to your repositories
enclosure. Otherwise you'll have to wait for jcenter to pick it up.

**Comment by stephanemaarek** [comment]
Okay I'll try tomorrow

**Comment by TonicArtos** [comment]
Actually, it turns out snapshots are a pain. I've made a release on MavenCentral instead. It'll take a couple of hours to sync... because MavenCentral. Anyway, when it has I'll check it and see if I got everything correct.
