### ISSUE TITLE
SuperSLIM crashes on a fling

### ISSUE THREAD

**Issue by brione** [TonicArtos/SuperSLiM#120]
I also noticed something I'd never seen before: as I scroll the grid, items relocate themselves in the grid, sometimes disappearing, or being moved to another group. I'll confirm that my adapter isn't reordering items. This just started today and I'd never seen it before.

Please let me know what other information we need to track down the cause of this.

Here is the stack backtrace I'm receiving:

E/AndroidRuntime(23691): FATAL EXCEPTION: main
E/AndroidRuntime(23691): Process: com.k2.android.k2startup, PID: 23691
E/AndroidRuntime(23691): java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.support.v7.widget.RecyclerView$ViewHolder.shouldIgnore()' on a null object reference
E/AndroidRuntime(23691):    at android.support.v7.widget.RecyclerView$LayoutManager.scrapOrRecycleView(RecyclerView.java:6589)
E/AndroidRuntime(23691):    at android.support.v7.widget.RecyclerView$LayoutManager.detachAndScrapViewAt(RecyclerView.java:6337)
E/AndroidRuntime(23691):    at com.tonicartos.superslim.GridSLM.fillToEnd(GridSLM.java:101)
E/AndroidRuntime(23691):    at com.tonicartos.superslim.LayoutManager.fillNextSectionToEnd(LayoutManager.java:745)
E/AndroidRuntime(23691):    at com.tonicartos.superslim.LayoutManager.fillNextSectionToEnd(LayoutManager.java:756)
E/AndroidRuntime(23691):    at com.tonicartos.superslim.LayoutManager.fillNextSectionToEnd(LayoutManager.java:756)
E/AndroidRuntime(23691):    at com.tonicartos.superslim.LayoutManager.fillNextSectionToEnd(LayoutManager.java:756)
E/AndroidRuntime(23691):    at com.tonicartos.superslim.LayoutManager.fillNextSectionToEnd(LayoutManager.java:756)
E/AndroidRuntime(23691):    at com.tonicartos.superslim.LayoutManager.fillNextSectionToEnd(LayoutManager.java:756)
E/AndroidRuntime(23691):    at com.tonicartos.superslim.LayoutManager.fillToEnd(LayoutManager.java:850)
E/AndroidRuntime(23691):    at com.tonicartos.superslim.LayoutManager.fillUntil(LayoutManager.java:908)
E/AndroidRuntime(23691):    at com.tonicartos.superslim.LayoutManager.scrollVerticallyBy(LayoutManager.java:361)
E/AndroidRuntime(23691):    at android.support.v7.widget.RecyclerView$ViewFlinger.run(RecyclerView.java:3777)
E/AndroidRuntime(23691):    at android.view.Choreographer$CallbackRecord.run(Choreographer.java:767)
E/AndroidRuntime(23691):    at android.view.Choreographer.doCallbacks(Choreographer.java:580)
E/AndroidRuntime(23691):    at android.view.Choreographer.doFrame(Choreographer.java:549)
E/AndroidRuntime(23691):    at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:753)
E/AndroidRuntime(23691):    at android.os.Handler.handleCallback(Handler.java:739)
E/AndroidRuntime(23691):    at android.os.Handler.dispatchMessage(Handler.java:95)
E/AndroidRuntime(23691):    at android.os.Looper.loop(Looper.java:135)
E/AndroidRuntime(23691):    at android.app.ActivityThread.main(ActivityThread.java:5221)
E/AndroidRuntime(23691):    at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(23691):    at java.lang.reflect.Method.invoke(Method.java:372)
E/AndroidRuntime(23691):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
E/AndroidRuntime(23691):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
W/ActivityManager( 1232):   Force finishing activity com.k2.android.k2startup/.activities.NavPanelMainActivity

**Comment by brione** [comment]
I have confirmed that my adapter is not doing any shuffling of the items during the scrolling and that I never attach a null view to my view holders.

**Comment by TonicArtos** [comment]
I think you found one of the flaws in the original design of the library. SuperSLiM tracks state through the attached views, but in recent versions of the SDK, sometimes I have seen what appeared to be empty views with no measured size getting dropped. I haven't looked into it further, but if this is happening then SuperSLiM can have a consistency problem and I can easily see the above problems happening.

Right now, I am working on what has become a rewrite of the library and should address this kind of problem. You can read about it on my [blog](tonicartos.com).

**Comment by frankjunqi** [comment]
hello, this question, ok??

**Comment by SKART1** [comment]
Looks like still not fixed. Have the same stack trace with simplest adapter on version 4.13
LayoutManager.LayoutParams.HEADER_INLINE  cause this crash to happen for me

**Comment by DSteve595** [comment]
Has this been fixed in version 5?

**Comment by TonicArtos** [comment]
The bug shouldn't happen again as there is a completely new approach in the new codebase. However, Grid view is not yet implemented in version 5, and I have to finish a couple of things before getting that. I did have a timeline on getting this done, but it has slipped as I've had other priorities come up for the short term.
