### ISSUE TITLE
Sticky header flickers if view partially behind it is clicked.

### ISSUE THREAD

**Issue by shivkumarmalik** [TonicArtos/SuperSLiM#125]
Hello,

I  am using inline sticky headers with LinearSLM.
If a view which is partially behind a sticky header is updated after a click and notifyDataSetChanged(viewPosition) is called, sticky header flickers. I know the header needs to be updated but the change is too much visible.

Would be grateful for any response.

Thanks and Regards :)

**Comment by vsahu1986** [comment]
+1

**Comment by TonicArtos** [comment]
Hi, I know about the many problems related to data changes. As much of the problems stem from a design flaw I have been rewriting the library. I am getting a test version ready for feedback soon. This version will be missing many features but should be ready for you to verify that the current problems are still not an issue, and to give feedback on the rest of the changes.

**Comment by vsahu1986** [comment]
Thanks ,appreciated

**Comment by edarn** [comment]
Any status update for this? I wouldn´t mind trying out a beta
