### ISSUE TITLE
onCreateViewHolder being called frequently and rapidly

### ISSUE THREAD

**Issue by kcorwin** [TonicArtos/SuperSLiM#13]
I noticed this in the app I'm working on, and it seems to be an issue in the example app as well. When I add logging statements to onCreateViewHolder (for example, in the CountryNamesAdapter in the example), I can see the method being called extremely frequently. Even a very slight scrolling movement will trigger tons of calls - as if it's happening for every redraw.  onBindViewHolder is called with the same frequency.

Since onCreateViewHolder is where the expensive operations (xml inflation, findViewById, etc) are supposed to live, this seems like a big performance hit.

**Comment by TonicArtos** [comment]
Thank you for your bug report.

On inspection this appears to be a caching problem related to computing the position of headers partially off-screen. I imagine there will always be performance issues related to this but once the caching problem is solved the spamming of onCreateViewHolder should calm down.

**Comment by TonicArtos** [comment]
@kcorwin, All the extraneous calls to onCreateViewHolder should now be fixed. Please use v0.2.1.

**Comment by kcorwin** [comment]
This is a huge improvement. Thanks for all your work on this!

**Comment by TonicArtos** [comment]
You're welcome. Please let me know if there is anything else you run into.
