### ISSUE TITLE
List move to bottom instead of the first item, when user updated the list in adapter and called notifyDataSetChanged

### ISSUE THREAD

**Issue by chandara** [TonicArtos/SuperSLiM#132]
When I update the list in my adapter and call notifyDataSetChanged, the recyclerview will move to bottom of list instead of the first item in the list.

**Comment by AndroidDeveloperLB** [comment]
is there a workaround for this? I'm trying to set new items list for the adapter, and then scroll to the top, but it doesn't scroll at all...
Is this the bug you encounter?

**Comment by AndroidDeveloperLB** [comment]
ok, found a workaround: use a handler.post(runnable) for scrolling.

**Comment by ansman** [comment]
Any news on this? Posting a runnable for scrolling causes an ugly glitch.
`LinearLayoutManager` will scroll to the top when `notifyDataSetChanged` is called but not when `notifyItemAdded` is called for example.
