### ISSUE TITLE
Request: update to latest versions of the SDK and support library

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [TonicArtos/SuperSLiM#135]
as the title says.

**Comment by TonicArtos** [comment]
There must have been a time out in fetching the script from GitHub.

**Comment by AndroidDeveloperLB** [comment]
@TonicArtos Please ignore the previous post I've written here. It was an issue on Android Studio. Now it's fine, so I've updated the question to something else...

**Comment by TonicArtos** [comment]
@AndroidDeveloperLB Yeah, I have that and a few other things to do on this. I'll get it done tonight or tomorrow.

**Comment by AndroidDeveloperLB** [comment]
Maybe you could use the gradle.properties file, so that in future versions of the SDK and support library, people could just set it there, instead of telling you to update it in the library itself.

Example:

gradle.properties

#used for compileSdkVersion
ANDROID_BUILD_SDK_VERSION = 22
#used for buildToolsVersion
ANDROID_BUILD_TOOLS_VERSION = 22.0.1
#used for minSdkVersion
ANDROID_BUILD_MIN_SDK_VERSION = 14
#used for targetSdkVersion
ANDROID_BUILD_TARGET_SDK_VERSION = 22


And in the build.gradle file of the library:

    compileSdkVersion Integer.parseInt(project.ANDROID_BUILD_SDK_VERSION)
    buildToolsVersion project.ANDROID_BUILD_TOOLS_VERSION
...
        minSdkVersion Integer.parseInt(project.ANDROID_BUILD_MIN_SDK_VERSION)
        targetSdkVersion Integer.parseInt(project.ANDROID_BUILD_TARGET_SDK_VERSION)

**Comment by AndroidDeveloperLB** [comment]
It's not a full example, but it's a start...

**Comment by TonicArtos** [comment]
True, I hadn't considered that. It won't work for all sdk configurations, but it should remove the problem for minor differences.

**Comment by AndroidDeveloperLB** [comment]
What do you mean it won't work?
You just put a requirement on the main page of the repo.
Also, the values used in the library itself should be an indication for
what the library really needs, so whoever uses it shouldn't complain if he
changed the value to something that's not supported.

**Comment by TonicArtos** [comment]
I was just discussing the caveat. Anyway, it is a good idea and I'll use it.

**Comment by AndroidDeveloperLB** [comment]
Thank you.
Say, can you also add fast-scroller to the RecyclerView?
I've done it myself, but not while using your own library too.
If you wish, you can use it:
https://github.com/AndroidDeveloperLB/LollipopContactsRecyclerViewFastScroller

You can also try my other small repos.

**Comment by TonicArtos** [comment]
I'd like to get there soon. At the moment I am rebuilding the library around nested sections because I need that in one of my projects. That work is a big reason why things have been quite delayed.

**Comment by AndroidDeveloperLB** [comment]
Say, I'm thinking of using this repo. How do I make the items appear in ListView style, instead of GridView style? I can't find where you've set it to be in grid.
The weird thing is that "text_line_item.xml" shows that it has a width of "match_parent", but this doesn't seem to affect the view inside the RecyclerView.
