### ISSUE TITLE
How to use List-style instead of Grid-style?

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [TonicArtos/SuperSLiM#137]
I'm thinking of using this repo. 

How do I make the items appear in ListView style, instead of GridView style? I can't find where you've set it to be in grid.

The weird thing is that "text_line_item.xml" shows that it has a width of "match_parent", but this doesn't seem to affect the view inside the RecyclerView.

**Comment by AndroidDeveloperLB** [comment]
I've tried removing this line from the CounrtyNameAdapter :

lp.setColumnWidth(mContext.getResources().getDimensionPixelSize(R.dimen.grid_column_width));

and it seems to fix this. Is it the correct way to make it list-style?

Also, it seems that adding a clickListener is problematic, as it includes the header as an item like other items, so using viewHolder.getAdapterPosition() will return the wrong number...
What should be done?

**Comment by brione** [comment]
In the example code:


        }
        lp.setSlm(item.sectionManager == LINEAR ? LinearSLM.ID : GridSLM.ID);
        lp.setColumnWidth(mContext.getResources().getDimensionPixelSize(R.dimen.grid_column_width));
        lp.setFirstPosition(item.sectionFirstPosition);

The line above the line you changed, is where he alternates between linear and grid layouts. That is how you choose which layout you want to use.

Or maybe I don't understand your question.

**Comment by AndroidDeveloperLB** [comment]
I think this will cause the headers also appear in a listView style, instead of being to the left of the normal items, no?

**Comment by TonicArtos** [comment]
In your adapter just do this.
```java
    final LayoutParams params = holder.getLayoutParams();
    params.setSlm(LinearSLM.ID); 
    params.setFirstPosition(item.sectionFirstPosition);
    holder.setLayoutParams(params);
```

To customize the header, it is easiest to use a different layout and view type, as is done in the example. In your header layout just set `slm_headerDisplay` to your desired configuration.

The documentation for the layout attributes is [here](https://github.com/TonicArtos/SuperSLiM/wiki/Attributes-and-Parameters-Reference).

From your comments I think this is something like what you are wanting in your header.
```xml
<TextView
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="wrap_content"
    android:layout_height="wrap_content"

    app:slm_headerDisplay="start|sticky"
    app:slm_isHeader="true"
    app:slm_section_headerMarginStart="56dip"
    />
```

**Comment by AndroidDeveloperLB** [comment]
I see, so the "sectionManager" is used to determine something that's related to grid vs list?
If so, I suggest changing its name. I thought it was crucial for working as it should.

I do have a weird bug though, which I didn't have with ListView: for each item, I load an image in the background (in ListView, it was in getView, but here it's in onBindViewHolder), and once it's done, I set it to the ImageView of the ViewHolder (while checking that its position hasn't changed).
For some reason, I don't see the image, unless I scroll enough and go back to the item.
Do you have any clue about why it occurs?

**Comment by AndroidDeveloperLB** [comment]
The bug occurs only when I use a ViewSwitcher (switching between loading state and real content of the imageView). odd. 
As a workaround, I've put a FrameLayout instead, but I don't get why it occurs.

**Comment by TonicArtos** [comment]
Hi, sorry that it has been a long time. There is a new design being implemented for version 5 and I just reached my first major Milestone. I'd be curious to know what you think of it, it also works with views in a standard manner so you should be free of any strangeness like you have encountered. You can find the new version on the [version5 branch](https://github.com/TonicArtos/SuperSLiM/tree/version5).

#### About version 5

Version 5 is a new implementation of SuperSLiM that works using an internal graph of your data set. This solves many problems with the old design. In Milestone 1, version 5 will render your data set as a graph of sections and items. It supports horizontal and vertical configurations, in addition to the other common layout configurations for RecyclerView. Oh yes, it also works with RecyclerView's predictive animations. The design is also simpler to use and easier to extend. However, right now that actual layout is incomplete as it does not scroll.

Milestone 2 is focused on bringing the library up to a usable point. It will add scrolling, a complete linear section layout, a complete set of header layouts, and a few other things. There are a few more planned milestones too. Please see the [project plan](https://trello.com/b/g3Wctuey) for more information.

**Comment by AndroidDeveloperLB** [comment]
@TonicArtos Please update the various versions in the repo.
