### ISSUE TITLE
Add alphabetical sideindex at scrollbar

### ISSUE THREAD

**Issue by ChrisDolge** [TonicArtos/SuperSLiM#138]
Hi 

Is it possible to add a alphabetical sideindex at the scrollbar ? For jumping to a special character in list.

**Comment by ChrisDolge** [comment]
Fixed

**Comment by debjitk** [comment]
How did you fixed it ?

**Comment by chrissd23** [comment]
Hi

I create a extra ItemDecoration wich implement an alphabetical sideindex. After that I add this to the recyclerview.

It works fine for me.
