### ISSUE TITLE
it is possible to combine with other kind of list view?

### ISSUE THREAD

**Issue by yfsx** [TonicArtos/SuperSLiM#145]
Hi, i just wondering if this list view can be combined with other kind of list view? for example, indexable list view (like iOS)?

thanks, great job BTW

**Comment by TonicArtos** [comment]
No, unfortunately not. However, it is planned to add fast scrolling in the future. Please see the [project plan](https://trello.com/b/g3Wctuey). Also, check out the [version 5 development branch](https://github.com/TonicArtos/SuperSLiM/tree/version5). It is not yet complete, but it is enough to get a good idea of how much better SuperSLiM will be very soon.
