### ISSUE TITLE
computeVerticalScrollOffset does not take into account headers

### ISSUE THREAD

**Issue by dirkvranckaert** [TonicArtos/SuperSLiM#151]
I'm using SuperSLiM for a few weeks now because I need to have sticky headers.
In my situation there is a ViewPager (with tabbar), the ViewPager has a SwipeRefreshLayout around it, and the ViewPager has two pages with each a list (RecyclerView). Both list are being setup with SuperSLiM for sticky headers.

Because the SwipeRefreshLayout overrules the scrolling in my RecyclerView I added this piece of code:

```
mRefresh.getViewTreeObserver().addOnScrollChangedListener(new OnScrollChangedListener() {
            @Override
            public void onScrollChanged() {
                RecyclerView list = mAdapter.getListFor(mCurrentPage);
                if (list != null) {
                    if (list.computeVerticalScrollOffset() == 0) {
                        mRefresh.setEnabled(true);
                    } else {
                        mRefresh.setEnabled(false);
                    }
                }
            }
        });
```

That all seems to work fine as long as my first item is not just under my first header, but really off screen. If the first item is only scrolled just a little under the header, the `list.computeVerticalScrollOffset()` (which get's redirected to the SuperSLiM LayoutManager (I double checked that with debugging)) returns 0. However in my opinion it should take into account the header that is still visible and it should not return 0 but it should return how many pixels my first item is scrolled under the header.

Here is my header XML (my header is smaller in height than my list items!):

```
<?xml version="1.0" encoding="utf-8"?>
<TextView xmlns:android="http://schemas.android.com/apk/res/android"
          xmlns:app="http://schemas.android.com/apk/res-auto"
          android:layout_width="match_parent"
          android:layout_height="wrap_content"
          android:paddingLeft="@dimen/horizontal_margin"
          android:paddingRight="@dimen/horizontal_margin"
          android:paddingTop="@dimen/vertical_margin"
          android:paddingBottom="@dimen/vertical_margin"
          android:lines="1"
          android:maxLines="1"
          android:singleLine="true"
          android:ellipsize="end"
          android:id="@+id/show_name"
          android:textSize="24sp"
          android:textStyle="bold"
          android:background="@android:color/white"
          app:slm_headerDisplay="inline|sticky"
          app:slm_isHeader="true"/>
```

**Comment by TonicArtos** [comment]
I'll be coming back to the scroll computation soon.
