### ISSUE TITLE
NullPointerException error

### ISSUE THREAD

**Issue by rhychel** [TonicArtos/SuperSLiM#152]
Hi, 

When I called the method recyclerView.smoothScrollToPosition(0); the app crashes.

 Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.os.Handler.post(java.lang.Runnable)' on a null object reference
            at com.tonicartos.superslim.LayoutManager.smoothScrollToPosition(LayoutManager.java:413)
            at android.support.v7.widget.RecyclerView.smoothScrollToPosition(RecyclerView.java:1377)

**Comment by TonicArtos** [comment]
Yes, this is a problem. Version 5 will not have this. Just so you know, development for SuperSLiM has moved entirely to version 5 and I am not making any updates to older versions.

Version 5 isn't yet usable, but has already solved a lot of outstanding problems. Milestone 1 for version 5 has just been reached and, if you check out the branch [version5](https://github.com/TonicArtos/SuperSLiM/tree/version5), you will find a new implementation of SuperSLiM that works using an internal graph of your data set. This solves many problems with the old design. In Milestone 1, version 5 will render your data set as a graph of sections and items. It supports horizontal and vertical configurations, in addition to the other common layout configurations for RecyclerView. Oh yes, it also works with RecyclerViews predictive animations. The design is also simpler to use and easier to extend. However, right now that actual layout is incomplete as it does not scroll.

Milestone 2 is focused on bringing the library up to a usable point. It will add scrolling, a complete linear section layout, a complete set of header layouts, and a few other things. There are a few more planned milestones too. Please see the [project plan](https://trello.com/b/g3Wctuey) for more information.
