### ISSUE TITLE
Null Pointer Exception on LayoutManager.getAnchorAtEnd

### ISSUE THREAD

**Issue by jlmalone** [TonicArtos/SuperSLiM#155]
Stack Trace

---

0   java.lang.NullPointerException: Attempt to invoke virtual method 'android.view.ViewGroup$LayoutParams android.view.View.getLayoutParams()' on a null object reference
1       at com.tonicartos.superslim.LayoutManager.getAnchorAtEnd(SourceFile:1038)
2       at com.tonicartos.superslim.LayoutManager.fillNextSectionToEnd(SourceFile:725)
3       at com.tonicartos.superslim.LayoutManager.layoutChildren(SourceFile:3369)
4                                              onLayoutChildren
5       at android.support.v7.widget.RecyclerView.dispatchLayout(SourceFile:2847)
6       at android.support.v7.widget.RecyclerView.resumeRequestLayout(SourceFile:1599)
7       at android.support.v7.widget.RecyclerView$1.run(SourceFile:277)
8       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:767)
9       at android.view.Choreographer.doCallbacks(Choreographer.java:580)
10      at android.view.Choreographer.doFrame(Choreographer.java:549)
11      at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:753)
12      at android.os.Handler.handleCallback(Handler.java:739)
13      at android.os.Handler.dispatchMessage(Handler.java:95)
14      at android.os.Looper.loop(Looper.java:135)
15      at android.app.ActivityThread.main(ActivityThread.java:5292)
16      at java.lang.reflect.Method.invoke(Native Method)
17      at java.lang.reflect.Method.invoke(Method.java:372)
18      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
19      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)

Threads

---

Thread: pool-3-thread-1
0       at java.lang.Object.wait(Native Method)
1       at java.lang.Thread.parkFor(Thread.java:1220)
2       at sun.misc.Unsafe.park(Unsafe.java:299)
3       at java.util.concurrent.locks.LockSupport.park(LockSupport.java:157)
4       at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2016)
5       at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:410)
6       at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1035)
7       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1097)
8       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
9       at java.lang.Thread.run(Thread.java:818)

Thread: Chrome_IOThread

Thread: fifo-pool-thread-0
0       at java.lang.Object.wait(Native Method)
1       at java.lang.Thread.parkFor(Thread.java:1220)
2       at sun.misc.Unsafe.park(Unsafe.java:299)
3       at java.util.concurrent.locks.LockSupport.park(LockSupport.java:157)
4       at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2016)
5       at java.util.concurrent.PriorityBlockingQueue.take(PriorityBlockingQueue.java:510)
6       at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1035)
7       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1097)
8       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
9       at java.lang.Thread.run(Thread.java:818)
10      at com.bumptech.glide.load.engine.executor.FifoPriorityThreadPoolExecutor$DefaultThreadFactory$1.run(SourceFile:118)

Thread: Chrome_FileUserBlockingThread

Thread: hwuiTask1

Thread: RenderThread

Thread: Signal Catcher

Thread: AsyncTask #2
0       at java.lang.Object.wait(Native Method)
1       at java.lang.Thread.parkFor(Thread.java:1220)
2       at sun.misc.Unsafe.park(Unsafe.java:299)
3       at java.util.concurrent.locks.LockSupport.park(LockSupport.java:157)
4       at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2016)
5       at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:410)
6       at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1035)
7       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1097)
8       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
9       at java.lang.Thread.run(Thread.java:818)

Thread: Thread-9928

Thread: Thread-9929

Thread: Binder_2

Thread: HeapTrimmerDaemon
0       at dalvik.system.VMRuntime.trimHeap(Native Method)
1       at java.lang.Daemons$HeapTrimmerDaemon.run(Daemons.java:313)
2       at java.lang.Thread.run(Thread.java:818)

Thread: FinalizerDaemon
0       at java.lang.Object.wait(Native Method)
1       at java.lang.Object.wait(Object.java:422)
2       at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:101)
3       at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:72)
4       at java.lang.Daemons$FinalizerDaemon.run(Daemons.java:174)
5       at java.lang.Thread.run(Thread.java:818)

Thread: OPTMZ
0       at com.android.org.conscrypt.NativeCrypto.SSL_do_handshake(Native Method)
1       at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:318)
2       at com.android.okhttp.Connection.upgradeToTls(Connection.java:201)
3       at com.android.okhttp.Connection.connect(Connection.java:155)
4       at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:276)
5       at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:211)
6       at com.android.okhttp.internal.http.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:382)
7       at com.android.okhttp.internal.http.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:106)
8       at com.android.okhttp.internal.http.HttpURLConnectionImpl.getOutputStream(HttpURLConnectionImpl.java:217)
9       at com.android.okhttp.internal.http.DelegatingHttpsURLConnection.getOutputStream(DelegatingHttpsURLConnection.java:218)
10      at com.android.okhttp.internal.http.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java:25)
11      at crittercism.android.h.a(Unknown Source)
12                            a
13                            a
14      at crittercism.android.h.run(Unknown Source)
15      at crittercism.android.cy.a(Unknown Source)
16      at crittercism.android.dc.run(Unknown Source)
17      at java.lang.Thread.run(Thread.java:818)

Thread: Thread-9925

Thread: fifo-pool-thread-1
0       at com.android.org.conscrypt.NativeCrypto.SSL_read(Native Method)
1       at com.android.org.conscrypt.OpenSSLSocketImpl$SSLInputStream.read(OpenSSLSocketImpl.java:699)
2       at crittercism.android.n.read(Unknown Source)
3                             read
4                             read
5       at com.android.okio.Okio$2.read(Okio.java:113)
6       at com.android.okio.RealBufferedSource.read(RealBufferedSource.java:48)
7       at com.android.okhttp.internal.http.HttpConnection$FixedLengthSource.read(HttpConnection.java:446)
8       at com.android.okio.RealBufferedSource$1.read(RealBufferedSource.java:168)
9       at java.io.FilterInputStream.read(FilterInputStream.java:118)
10      at com.bumptech.glide.util.ContentLengthInputStream.read(SourceFile:65)
11      at com.bumptech.glide.util.ContentLengthInputStream.read(SourceFile:60)
12      at com.bumptech.glide.load.resource.bitmap.RecyclableBufferedInputStream.fillbuf(SourceFile:132)
13      at com.bumptech.glide.load.resource.bitmap.RecyclableBufferedInputStream.read(SourceFile:309)
14      at java.io.InputStream.read(InputStream.java:162)
15      at com.bumptech.glide.load.resource.bitmap.RecyclableBufferedInputStream.fillbuf(SourceFile:132)
16      at com.bumptech.glide.load.resource.bitmap.RecyclableBufferedInputStream.read(SourceFile:309)
17      at com.bumptech.glide.util.ExceptionCatchingInputStream.read(SourceFile:84)
18      at java.io.FilterInputStream.read(FilterInputStream.java:118)
19      at com.bumptech.glide.util.MarkEnforcingInputStream.read(SourceFile:44)
20      at android.graphics.BitmapFactory.nativeDecodeStream(Native Method)
21      at android.graphics.BitmapFactory.decodeStreamInternal(BitmapFactory.java:635)
22      at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:611)
23      at com.bumptech.glide.load.resource.bitmap.Downsampler.getSampleSize(SourceFile:329)
24                                                          decodeStream
25      at com.bumptech.glide.load.resource.bitmap.Downsampler.downsampleWithSize(SourceFile:2220)
26                                                          decode
27                                                          getSampleSize
28      at com.bumptech.glide.load.resource.bitmap.StreamBitmapDecoder.decode(SourceFile:1050)
29                                                                  decode
30      at com.bumptech.glide.load.resource.bitmap.ImageVideoBitmapDecoder.decode(SourceFile:39)
31      at com.bumptech.glide.load.resource.bitmap.ImageVideoBitmapDecoder.decode(SourceFile:20)
32      at com.bumptech.glide.load.resource.gifbitmap.GifBitmapWrapperResourceDecoder.decodeBitmapWrapper(SourceFile:121)
33      at com.bumptech.glide.load.resource.gifbitmap.GifBitmapWrapperResourceDecoder.decodeStream(SourceFile:1094)
34                                                                                 decode
35                                                                                 decode
36      at com.bumptech.glide.load.resource.gifbitmap.GifBitmapWrapperResourceDecoder.decode(SourceFile:22)
37      at com.bumptech.glide.load.engine.DecodeJob.decodeFromSourceData(SourceFile:2190)
38                                               decodeSource
39      at com.bumptech.glide.load.engine.DecodeJob.decodeFromSource(SourceFile:128)
40      at com.bumptech.glide.load.engine.EngineRunnable.decodeFromSource(SourceFile:1122)
41                                                    decode
42                                                    run
43      at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
44      at java.util.concurrent.FutureTask.run(FutureTask.java:237)
45      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
46      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
47      at java.lang.Thread.run(Thread.java:818)
48      at com.bumptech.glide.load.engine.executor.FifoPriorityThreadPoolExecutor$DefaultThreadFactory$1.run(SourceFile:118)

Thread: Binder_1

Thread: OkHttp ConnectionPool
0       at java.lang.Object.wait(Native Method)
1       at com.squareup.okhttp.ConnectionPool.performCleanup(SourceFile:304)
2       at com.squareup.okhttp.ConnectionPool.runCleanupUntilPoolIsEmpty(SourceFile:241)
3       at com.squareup.okhttp.ConnectionPool.access$000(SourceFile:54)
4       at com.squareup.okhttp.ConnectionPool$1.run(SourceFile:97)
5       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
6       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
7       at java.lang.Thread.run(Thread.java:818)

Thread: Thread-9930

Thread: ReferenceQueueDaemon
0       at java.lang.Object.wait(Native Method)
1       at java.lang.Daemons$ReferenceQueueDaemon.run(Daemons.java:134)
2       at java.lang.Thread.run(Thread.java:818)

Thread: GCDaemon
0       at java.lang.Object.wait(Native Method)
1       at java.lang.Daemons$GCDaemon.run(Daemons.java:344)
2       at java.lang.Thread.run(Thread.java:818)

Thread: Thread-9891
0       at java.lang.Object.wait(Native Method)
1       at java.lang.Thread.parkFor(Thread.java:1220)
2       at sun.misc.Unsafe.park(Unsafe.java:299)
3       at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:197)
4       at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2055)
5       at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1060)
6       at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:776)
7       at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1035)
8       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1097)
9       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
10      at crittercism.android.cy.a(Unknown Source)
11      at crittercism.android.dc.run(Unknown Source)
12      at java.lang.Thread.run(Thread.java:818)

Thread: Chrome_FileThread

Thread: AsyncTask #3
0       at java.lang.Object.wait(Native Method)
1       at java.lang.Thread.parkFor(Thread.java:1220)
2       at sun.misc.Unsafe.park(Unsafe.java:299)
3       at java.util.concurrent.locks.LockSupport.park(LockSupport.java:157)
4       at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2016)
5       at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:410)
6       at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1035)
7       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1097)
8       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
9       at java.lang.Thread.run(Thread.java:818)

Thread: AsyncTask #4
0       at java.lang.Object.wait(Native Method)
1       at java.lang.Thread.parkFor(Thread.java:1220)
2       at sun.misc.Unsafe.park(Unsafe.java:299)
3       at java.util.concurrent.locks.LockSupport.park(LockSupport.java:157)
4       at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2016)
5       at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:410)
6       at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1035)
7       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1097)
8       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
9       at java.lang.Thread.run(Thread.java:818)

Thread: fifo-pool-thread-3
0       at java.lang.Object.wait(Native Method)
1       at java.lang.Thread.parkFor(Thread.java:1220)
2       at sun.misc.Unsafe.park(Unsafe.java:299)
3       at java.util.concurrent.locks.LockSupport.park(LockSupport.java:157)
4       at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2016)
5       at java.util.concurrent.PriorityBlockingQueue.take(PriorityBlockingQueue.java:510)
6       at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1035)
7       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1097)
8       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
9       at java.lang.Thread.run(Thread.java:818)
10      at com.bumptech.glide.load.engine.executor.FifoPriorityThreadPoolExecutor$DefaultThreadFactory$1.run(SourceFile:118)

Thread: Chrome_CacheThread

Thread: OkHttp ConnectionPool
0       at java.lang.Object.wait(Native Method)
1       at java.lang.Thread.parkFor(Thread.java:1220)
2       at sun.misc.Unsafe.park(Unsafe.java:299)
3       at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:197)
4       at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2055)
5       at java.util.concurrent.LinkedBlockingQueue.poll(LinkedBlockingQueue.java:435)
6       at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1035)
7       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1097)
8       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
9       at java.lang.Thread.run(Thread.java:818)

Thread: Okio Watchdog
0       at java.lang.Object.wait(Native Method)
1       at okio.AsyncTimeout.awaitTimeout(SourceFile:297)
2       at okio.AsyncTimeout.access$000(SourceFile:40)
3       at okio.AsyncTimeout$Watchdog.run(SourceFile:272)

Thread: fifo-pool-thread-2
0       at java.lang.Object.wait(Native Method)
1       at java.lang.Thread.parkFor(Thread.java:1220)
2       at sun.misc.Unsafe.park(Unsafe.java:299)
3       at java.util.concurrent.locks.LockSupport.park(LockSupport.java:157)
4       at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2016)
5       at java.util.concurrent.PriorityBlockingQueue.take(PriorityBlockingQueue.java:510)
6       at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1035)
7       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1097)
8       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
9       at java.lang.Thread.run(Thread.java:818)
10      at com.bumptech.glide.load.engine.executor.FifoPriorityThreadPoolExecutor$DefaultThreadFactory$1.run(SourceFile:118)

Thread: pool-2-thread-1
0       at java.lang.Object.wait(Native Method)
1       at java.lang.Thread.parkFor(Thread.java:1220)
2       at sun.misc.Unsafe.park(Unsafe.java:299)
3       at java.util.concurrent.locks.LockSupport.park(LockSupport.java:157)
4       at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2016)
5       at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:410)
6       at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1035)
7       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1097)
8       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
9       at java.lang.Thread.run(Thread.java:818)

Thread: FinalizerWatchdogDaemon
0       at java.lang.Thread.sleep(Native Method)
1       at java.lang.Thread.sleep(Thread.java:1031)
2       at java.lang.Thread.sleep(Thread.java:985)
3       at java.lang.Daemons$FinalizerWatchdogDaemon.sleepFor(Daemons.java:258)
4       at java.lang.Daemons$FinalizerWatchdogDaemon.waitForFinalization(Daemons.java:269)
5       at java.lang.Daemons$FinalizerWatchdogDaemon.run(Daemons.java:217)
6       at java.lang.Thread.run(Thread.java:818)

Thread: AsyncTask #5
0       at java.lang.Object.wait(Native Method)
1       at java.lang.Thread.parkFor(Thread.java:1220)
2       at sun.misc.Unsafe.park(Unsafe.java:299)
3       at java.util.concurrent.locks.LockSupport.park(LockSupport.java:157)
4       at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2016)
5       at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:410)
6       at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1035)
7       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1097)
8       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
9       at java.lang.Thread.run(Thread.java:818)

Thread: Chrome_ProcessLauncherThread

Thread: fifo-pool-thread-0
0       at java.lang.Object.wait(Native Method)
1       at java.lang.Thread.parkFor(Thread.java:1220)
2       at sun.misc.Unsafe.park(Unsafe.java:299)
3       at java.util.concurrent.locks.LockSupport.park(LockSupport.java:157)
4       at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2016)
5       at java.util.concurrent.PriorityBlockingQueue.take(PriorityBlockingQueue.java:510)
6       at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1035)
7       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1097)
8       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
9       at java.lang.Thread.run(Thread.java:818)
10      at com.bumptech.glide.load.engine.executor.FifoPriorityThreadPoolExecutor$DefaultThreadFactory$1.run(SourceFile:118)

Thread: Thread-9897
0       at java.lang.Object.wait(Native Method)
1       at java.lang.Thread.parkFor(Thread.java:1220)
2       at sun.misc.Unsafe.park(Unsafe.java:299)
3       at java.util.concurrent.locks.LockSupport.park(LockSupport.java:157)
4       at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2016)
5       at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:410)
6       at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1035)
7       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1097)
8       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
9       at crittercism.android.cy.a(Unknown Source)
10      at crittercism.android.dc.run(Unknown Source)
11      at java.lang.Thread.run(Thread.java:818)

Thread: pool-4-thread-1
0       at java.lang.Object.wait(Native Method)
1       at java.lang.Thread.parkFor(Thread.java:1220)
2       at sun.misc.Unsafe.park(Unsafe.java:299)
3       at java.util.concurrent.locks.LockSupport.park(LockSupport.java:157)
4       at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2016)
5       at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:410)
6       at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1035)
7       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1097)
8       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
9       at java.lang.Thread.run(Thread.java:818)

Thread: cr.CleanupReference
0       at java.lang.Object.wait(Native Method)
1       at java.lang.Object.wait(Object.java:422)
2       at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:101)
3       at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:72)
4       at org.chromium.content.common.CleanupReference$1.run(CleanupReference.java:51)

Thread: hwuiTask2

Thread: Binder_3

Thread: AsyncTask #1
0       at java.lang.Object.wait(Native Method)
1       at java.lang.Thread.parkFor(Thread.java:1220)
2       at sun.misc.Unsafe.park(Unsafe.java:299)
3       at java.util.concurrent.locks.LockSupport.park(LockSupport.java:157)
4       at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2016)
5       at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:410)
6       at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1035)
7       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1097)
8       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
9       at java.lang.Thread.run(Thread.java:818)

Thread: Chrome_DBThread

Thread: pool-5-thread-1
0       at java.lang.Object.wait(Native Method)
1       at java.lang.Thread.parkFor(Thread.java:1220)
2       at sun.misc.Unsafe.park(Unsafe.java:299)
3       at java.util.concurrent.locks.LockSupport.park(LockSupport.java:157)
4       at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2016)
5       at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:410)
6       at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1035)
7       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1097)
8       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
9       at java.lang.Thread.run(Thread.java:818)

Thread: Thread-9924

Thread: Thread-9926

Thread: TXN Thread
0       at java.lang.Object.wait(Native Method)
1       at android.os.ConditionVariable.block(ConditionVariable.java:97)
2       at crittercism.android.ba.a(Unknown Source)
3                              a
4       at crittercism.android.dc.run(Unknown Source)
5       at crittercism.android.cy.a(Unknown Source)
6       at crittercism.android.dc.run(Unknown Source)
7       at java.lang.Thread.run(Thread.java:818)

**Comment by z0rawar** [comment]
Same here!

**Comment by tonyAndr** [comment]
same...

**Comment by chrissd23** [comment]
same here , @TonicArtos any suggestion .....?

**Comment by ryanamaral** [comment]
same problem!

**Comment by mobiRic** [comment]
bump - with a slightly different stack trace

java.lang.NullPointerException
  at com.tonicartos.superslim.LayoutManager.getAnchorAtEnd(LayoutManager.java:1038)
  at com.tonicartos.superslim.LayoutManager.fillNextSectionToEnd(LayoutManager.java:725)
  at com.tonicartos.superslim.LayoutManager.layoutChildren(LayoutManager.java:1369)
  at com.tonicartos.superslim.LayoutManager.onLayoutChildren(LayoutManager.java:276)
  at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3026)
  at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:2903)
  at android.support.v7.widget.RecyclerView.consumePendingUpdateOperations(RecyclerView.java:1447)
  at android.support.v7.widget.RecyclerView.access$400(RecyclerView.java:147)
  at android.support.v7.widget.RecyclerView$1.run(RecyclerView.java:285)
  at android.view.Choreographer$CallbackRecord.run(Choreographer.java:749)

on version 0.4.13

**Comment by TonicArtos** [comment]
This won't happen in soon.

**Comment by jlmalone** [comment]
@TonicArtos Do you have a PR you are going to merge to fix this? From a high level it looks like the code has not been updated in a year.

**Comment by guytkix** [comment]
Has anybody found a solution/workaround for this?

**Comment by TonicArtos** [comment]
@jlmalone Sorry, I have been sitting on top of a big push for a while. I thought I almost had it all ready two weeks ago, but I ran into some issues passing some tests. I then realised I'd missed testing another part, and after I wrote those tests I discovered there were bugs in the layouts after I implemented scrolling. Which meant I've had to go back and look at both the normal, pre, and post layout code in addition to the scroll code. It has been a huge time sink and I am still in the middle of it.

**Comment by GaganKainth** [comment]
@TonicArtos same error different stacktrace on version 0.4.13:

java.lang.NullPointerException: Attempt to invoke virtual method 'android.view.ViewGroup$LayoutParams android.view.View.getLayoutParams()' on a null object reference
      at com.tonicartos.superslim.LayoutManager.getAnchorAtEnd(SourceFile:1038)
      at com.tonicartos.superslim.LayoutManager.fillNextSectionToEnd(SourceFile:725)
      at com.tonicartos.superslim.LayoutManager.layoutChildren(SourceFile:1369)
      at com.tonicartos.superslim.LayoutManager.onLayoutChildren(SourceFile:276)
      at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(SourceFile:3028)
      at android.support.v7.widget.RecyclerView.dispatchLayout(SourceFile:2906)
      at android.support.v7.widget.RecyclerView.onLayout(SourceFile:3283)
      at android.view.View.layout(View.java:16636)
      at android.view.ViewGroup.layout(ViewGroup.java:5437)
      at android.support.v4.widget.SwipeRefreshLayout.onLayout(SourceFile:596)
      at android.view.View.layout(View.java:16636)
      at android.view.ViewGroup.layout(ViewGroup.java:5437)
      at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1079)
      at android.view.View.layout(View.java:16636)
      at android.view.ViewGroup.layout(ViewGroup.java:5437)
      at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
      at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
      at android.view.View.layout(View.java:16636)
      at android.view.ViewGroup.layout(ViewGroup.java:5437)
      at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1079)
      at android.view.View.layout(View.java:16636)
      at android.view.ViewGroup.layout(ViewGroup.java:5437)
      at android.support.design.widget.CoordinatorLayout.layoutChild(SourceFile:1091)
      at android.support.design.widget.CoordinatorLayout.onLayoutChild(SourceFile:801)
      at android.support.design.widget.CoordinatorLayout.onLayout(SourceFile:815)
      at android.view.View.layout(View.java:16636)
      at android.view.ViewGroup.layout(ViewGroup.java:5437)
      at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
      at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
      at android.view.View.layout(View.java:16636)
      at android.view.ViewGroup.layout(ViewGroup.java:5437)
      at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1743)
      at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1586)
      at android.widget.LinearLayout.onLayout(LinearLayout.java:1495)
      at android.view.View.layout(View.java:16636)
      at android.view.ViewGroup.layout(ViewGroup.java:5437)
      at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
      at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
      at android.view.View.layout(View.java:16636)
      at android.view.ViewGroup.layout(ViewGroup.java:5437)
      at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1743)
      at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1586)
      at android.widget.LinearLayout.onLayout(LinearLayout.java:1495)
      at android.view.View.layout(View.java:16636)
      at android.view.ViewGroup.layout(ViewGroup.java:5437)
      at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
      at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
      at com.android.internal.policy.PhoneWindow$DecorView.onLayout(PhoneWindow.java:2678)
      at android.view.View.layout(View.java:16636)
      at android.view.ViewGroup.layout(ViewGroup.java:5437)
      at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2171)
      at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1931)
      at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1107)
      at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6013)
      at android.view.Choreographer$CallbackRecord.run(Choreographer.java:858)
      at android.view.Choreographer.doCallbacks(Choreographer.java:670)
      at android.view.Choreographer.doFrame(Choreographer.java:606)
      at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:844)
      at android.os.Handler.handleCallback(Handler.java:739)
      at android.os.Handler.dispatchMessage(Handler.java:95)
      at android.os.Looper.loop(Looper.java:148)
      at android.app.ActivityThread.main(ActivityThread.java:5417)
      at java.lang.reflect.Method.invoke(Native Method)
      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by komissarovdenis** [comment]
any updates? 
have same error

**Comment by emilpradeep** [comment]
Gettting exactly the same error @tonyAndr .
