### ISSUE TITLE
Issues using grid layout manager with single column with SwipeRefreshLayout

### ISSUE THREAD

**Issue by ZOlbrys** [TonicArtos/SuperSLiM#156]
When using the GridSLM layout manager with a single column on a RecyclerView wrapped with a SwipeRefreshLayout, only the first RecyclerView view can be interacted with (i.e. touch listeners on views contained in this work, etc.)  Other views are displayed - but they are not working properly, and are reported to be detached from the window.

To make a quick sample app:
1. Add library to gradle
2. Add RecyclerView with SwipeRefreshLayout parent in XML layout file
3. Create a dummy adapter with data, setup a dummy layout for the RecyclerView views as well.
4. Setup the recycler view to use the SuperSLiM layout manager.
5. In onBindViewHolder for the adapter, setup the layout params of the holder.itemView to use GridSLM.LayoutParams with 1 column and the GridSLM.ID slm value.
6. Also bind some sort of interaction on the view holder, to indicate it has been clicked (show a toast when the view is clicked, etc.)

Expected result:
Tapping any of the views in the single column grid layout should be clickable/able to be interacted with.

Actual result:
Only the first view can be clicked.  All other views do not work.  After scrolling the recycler view a bit (such that the view is not at y position 0), all views can be clicked.

Not using a SwipeRefreshLayout around the RecyclerView causes this issue to disappear.  Two column layouts appear to work okay as well, but may still have issues, I'm still trying this out...

Any thoughts on what is happening?

Edit: some more notes/observations
1. I am not using sections in this case.  I know the use case of not using headers make this library unnecessary, but I am reusing the same fragment/logic containing my RecyclerView in multiple places.  In some places the headers should show, in others the header should not be displayed.
2. Two column layouts also do not behave correctly.  Only the first view and all views in the second column work, any view in the first column except for the first one do not.  Very odd.

**Comment by TonicArtos** [comment]
This is a design flaw in v0.4. The design was stateless and views were being bound and recycled many times to build section state and position things properly. The fix, v0.5 is coming very soon, it'll probably be a Christmas present.

**Comment by ZOlbrys** [comment]
Thanks, good to hear.

**Comment by TonicArtos** [comment]
If you check out the branch [version5](https://github.com/TonicArtos/SuperSLiM/tree/version5), you will find a new implementation of SuperSLiM that works using an internal graph of your data set. It does not yet scroll and currently only displays sections linearly, but I'd be curious to know if you have this problem on the new code base, you shouldn't.

**Comment by ZOlbrys** [comment]
I will give version5 a try when I have some free time, and will report back.
