### ISSUE TITLE
Is this project abandoned?

### ISSUE THREAD

**Issue by davideas** [TonicArtos/SuperSLiM#163]
Cannot compile your project with the most recent versions of Gradle and support libraries.
We have only the most recent version nowadays.

**Comment by Jaikant** [comment]
There doesn't seem to be any activity from the beginning of the year.

**Comment by davideas** [comment]
However, for who is interested, I've implemented a new way to display Sections and Sticky Headers using only the Adapter. The project is [FlexibleAdapter](https://github.com/davideas/FlexibleAdapter).
FlexibleAdapter has much more functionalities than only sections.

**Comment by DennyWeinberg** [comment]
@davideas: wow perfect. I will try it out and maybe replace super slim by this. Thank you for sharing.
I use it in my app: https://play.google.com/store/apps/details?id=com.levionsoftware.photos

**Comment by TonicArtos** [comment]
The project is not dead. I have had quite a lot of complication in life this year, but I have continued to work on SuperSLiM in my limited time. I know I have neglected maintaining this public repository and I am sorry for that.

@davideas Nice library. I am happy other people are also tackling similar problems.

**Comment by MartinRajniak** [comment]
@TonicArtos Thanks for the great work. Good to have you back.
