### ISSUE TITLE
SuperSLiM doesn't work with Android Support Library 23.2.1

### ISSUE THREAD

**Issue by AlvaroProjectPeople** [TonicArtos/SuperSLiM#173]

**Comment by kmare** [comment]
I guess you'll have to provide more info about your problem as 23.2.1 is working fine for me. Just tried 23.3.0 as well and it's all good (again, at least with my app).

**Comment by amirhgh** [comment]
I have same issue with Support Library 23.3.0, this problem exists even in the example.

**Comment by DennyWeinberg** [comment]
Same problem here. There are big display issues with the new android support library...

**Comment by gaoxuxu** [comment]
same problem

**Comment by TonicArtos** [comment]
I haven't checked in with 0.4 for a while now. However, I haven't seen any problems with 23.2.1 on the development branch for 0.5.

**Comment by DennyWeinberg** [comment]
I have problems with 23.3.0. someone changed the title of the issue...

**Comment by DennyWeinberg** [comment]
I found out why this happend in my case.
See http://stackoverflow.com/questions/35728179/recyclerview-items-with-big-empty-space-after-23-2-0

Just in case of someone has the same problem.

**Comment by ThanosFisherman** [comment]
I couldn't run the source code from version 5 in android studio. Tried to update all libs to latest but getting this error

> e: C:\Users\Thanos\Documents\AndroidstudioProjects\SuperSLiM\library\src\main\kotlin\com\tonicartos\superslim\internal\graph.kt: (24, 17): Out-projected type 'com.tonicartos.superslim.AdapterContract<*>' prohibits the use of 'public abstract fun setSectionIds(idMap: kotlin.collections.Map<ID, kotlin.Int>): kotlin.Unit defined in com.tonicartos.superslim.AdapterContract'
> e: C:\Users\Thanos\Documents\AndroidstudioProjects\SuperSLiM\library\src\main\kotlin\com\tonicartos\superslim\internal\graph.kt: (33, 37): Type mismatch: inferred type is kotlin.Pair<kotlin.Any?, com.tonicartos.superslim.SectionData> but kotlin.Pair<kotlin.Nothing, com.tonicartos.superslim.SectionData> was expected. Projected type com.tonicartos.superslim.AdapterContract<*> restricts use of public abstract fun populateSection(data: kotlin.Pair<ID, com.tonicartos.superslim.SectionData>): kotlin.Unit defined in com.tonicartos.superslim.AdapterContract
> :library:compileReleaseKotlin FAILED
> 
> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> Execution failed for task ':library:compileReleaseKotlin'.

**Comment by TonicArtos** [comment]
Yes, there was a language change in Kotlin when 1.0 was released. I have it fixed locally. You know what? I will make a push later today. It is still bugged but at least it will compile.

**Comment by EpariNigam** [comment]
@DennyWeinberg as you gave a link to check for match_parent issue, I checked with all the items and all are wrap_content. But, in my case its not working for the version 23.3.0

**Comment by TonicArtos** [comment]
@EpariNigam I'll see what I can get done by the 22nd.

**Comment by EpariNigam** [comment]
@TonicArtos have you found any solution, bcoz its very important for me and urgent for me.

**Comment by AlvaroProjectPeople** [comment]
With support library 23.4.0 and superslim 0.4.13 it's working for me.

Adapter:
`final GridSLM.LayoutParams params = GridSLM.LayoutParams.from(holder.itemView.getLayoutParams());
params.setSlm(LinearSLM.ID);
params.setFirstPosition(mItems.get(position).getSectionFirstPosition());
holder.itemView.setLayoutParams(params);`

**Comment by EpariNigam** [comment]
@AlvaroProjectPeople I am not using the library directly, I am downloading the zip and modifying the gradle file of library to use in project.

**Comment by TonicArtos** [comment]
@EpariNigam I took a few hours to try and fix the problem, but there is really too much to do there. Bascially, with the extensive architectural problems in v0.4 and now that version5 being so close to being usable, I've decided to not fix the problem. I am going to be away for a short time again, about a week, and then I'll be onto SuperSLiM full time for a while to push out a version ready for use by you and others.

#### Current state of version5 development
The adapter interface is tentatively stable. It needs feedback from more users. The architecture of SuperSLiM internally is stabilising. Abstracting orientation and layout direction variations has been stable for a long time (and is totally excellent). Overscroll is an outstanding problem I have yet to address fully; it remains to be seen how my intended solution will interact with RV animations.

Right now, I am just finishing up adding support for padding. The complication of which has delayed finishing scroll support. Also, there are still some semantics remaining for how scrolling down works. I have a straight forward design for this, but there may be niggles I haven't accounted for yet. Scrolling up works properly now including interaction with padding.

**Comment by divysoni3** [comment]
I am using compile 'com.android.support:recyclerview-v7:24.0.0' and in the fragment_main Changing the RecyclerView height from wrap_content to match_parent worked for me.

**Comment by yangpeiyong** [comment]
Changing the RecyclerView height from **wrap_content** to **match_parent**

**Comment by AbduazizKayumov** [comment]
Changing the RecyclerView height from wrap_content to match_parent worked for me
