### ISSUE TITLE
Need compatibility tests for RecyclerView lib versions.

### ISSUE THREAD

**Issue by TonicArtos** [TonicArtos/SuperSLiM#174]
I need to write some tests against RecyclerView to do a compatibility test. Of concern is item op reordering between calls of _notifyItemChanged_ and friends, and calls to _onItemChanged_ and friends on LayoutManager. v0.5 requires a certain behaviour and presently, versions <= 22.1 and 22.3 have that behaviour, 22.2 does not.

**Comment by simonwzb** [comment]
+1
