### ISSUE TITLE
ViewPager type of item (non-header) does not appear on the screen. Horizontal scrolling functionality does not work.

### ISSUE THREAD

**Issue by dkarmazidkarmazi** [TonicArtos/SuperSLiM#175]
Hello,

First of all, many thanks for this for this awesome library, it's very smooth and robust. I'm trying to build my solution around SuperSliM and ran into the following issue:

Whenever I use ViewPager type of item (non-header), the ViewPager will not appear on the screen. A simple scroll of pager off the screen and then scroll back on the screen, i.e. invoking onDetachToWindow/ onAttachedToWindow will reveal the pager. However, horizontal pager swiping functionality does not work. I'm using vertical LinearSLM.

in onCreateViewHolder:
`View v = LayoutInflater.from(context).inflate(R.layout.gallery_pager, parent, false);`
`return new CountryViewHolder(v);`

in gallery_pager:

```
<?xml version="1.0" encoding="utf-8"?>
<FrameLayout
    xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="wrap_content">

    <android.support.v4.view.ViewPager
        android:layout_width="match_parent"
        android:layout_height="300dp"
        android:background="#f00"
        android:id="@+id/gallery_pager"/>
</FrameLayout>
```

Here is the link to sample, sample is build off from your example: https://bitbucket.org/dkarmazi/androidsuperslimimpl/src

Any help would be much appreciated.

**Comment by TonicArtos** [comment]
View pager definitely won't work with superslim v0.4. It should with version5, which you can check out of the version5 branch. Be aware that version5 is massively incomplete. I am back working on it next week.

**Comment by dkarmazidkarmazi** [comment]
@TonicArtos, thank you for quick reply! I will definitely check out version5 branch. Do you roughly know the reason why ViewPager won't work with v0.4? Alternatively, would you recommend any specific area of code to look at in version5 that addresses this issue?

**Comment by TonicArtos** [comment]
In v0.4 there are probably two reasons for the problem with view pager. 1)
Views are measured before they are attached to the view hierarchy. 2) the
implementation sometimes reattaches and detaches views multiple times and
recycler view has some weird behaviour if this happens. Version5 does
neither of these, and is being written (rewritten) to interact with
recycler view as much like the stock layout managers as possible.

**Comment by dkarmazidkarmazi** [comment]
@TonicArtos thanks for your comments. I think I have figured out a temp workaround with ViewPagers. The solution is to invoke itemView.requestLayout in OnBindViewHolder via postDelayed, so that we do an extra measure and draw on the view once the view has been attached.

By no means this is a good solution, but rather an inefficient hack to make it working. However, I'm leaving it here just in case someone faces the same problem and needs it to be working asap.

Thanks again for your library and quick turnaround on the issue.

**Comment by RJFares** [comment]
I am having a very weird bug, which only happens if I use the slim LayoutManager for my recyclerview.
I have a viewpager which loads fragments with recyclerviews, each having a spinner.
When i change the fragment then get back to the same one, the spinners don't change their ItemSelected when a user selects an item (if I query what was clicked it does show correctly but the view doesn't update to reflect the new value in the spinner).
This happens only in viewpagers and in that very specific scenario, I have no idea how to report the bug.
It could be that it'll be solved by v5, but i've been holding the project release for a while and I have a deadline :\ any idea about the deadline of v5 release?
