### ISSUE TITLE
superslim layoutmanager provide loadmore method?

### ISSUE THREAD

**Issue by nightbear1009** [TonicArtos/SuperSLiM#19]
hi,
I'm using superslim in my project but I face a big problem to load more item when i am scrolling to the end of my data. 

In recyclerview to trigger loadmore method we need Layoutmanger to tell us some infomation
for example 
 int lastVisibleItem = ((LinearLayoutManager) mLayoutManager).findLastVisibleItemPosition();
                int totalItemCount = mLayoutManager.getItemCount();
                //lastVisibleItem >= totalItemCount - 4 

                if (lastVisibleItem >= totalItemCount - 4 && dy > 0) {
                    loadPage(currentQueryMap);
                }

can you provide some method for me?  thanks

**Comment by TonicArtos** [comment]
I don't see any problem with implementing the equivalent of [LinearLayoutManager.findLastVisibleItemPosition()](https://developer.android.com/reference/android/support/v7/widget/LinearLayoutManager.html#findLastVisibleItemPosition()).

**Comment by nightbear1009** [comment]
oh,  sorry for my mistake. I am using the wrong layoutmanager.
i will close this issue.  Thanks.

**Comment by TonicArtos** [comment]
Hang on, I thought you wanted findLastVisibleItemPosition() implemented on SuperSLiM.LayoutManager.

**Comment by nightbear1009** [comment]
yes, that's what I need.

**Comment by TonicArtos** [comment]
Duplicate of #22.

**Comment by TonicArtos** [comment]
Just to let you know. Fixed in v0.2.1.
