### ISSUE TITLE
Bug: headers might overlap items

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [TonicArtos/SuperSLiM#2]
Like so:

![device-2015-01-04-230839](https://cloud.githubusercontent.com/assets/5357526/5607489/ab25b872-9466-11e4-9cb3-511564aad99a.png)

BTW, please also check RTL . I remember there were issues on similar libraries when handling RTL languages, especially when the alignment changes. I didn't check this on this library yet. Hope it works well.

**Comment by TonicArtos** [comment]
RTL support is not yet done, and headers will overlap of they are overlay style headers. If the headers are not overlay or inline they should only be placed inside a margin area to the sides. If the margin area is too small they will clip off the sides of the screen. 

From your screen shot it looks like the header style is overlay_end, with an end margin of zero, so the overlap is working as intended.

**Comment by AndroidDeveloperLB** [comment]
oops, sorry, didn't notice that this is what I chose .
However, when choosing "right" (which is what I wanted to choose), I don't see the headers at all.

**Comment by TonicArtos** [comment]
When the example app has 'fixed' margins it has a 56dip left margin and a 0dip right margin. When the header is left or right aligned it is positioned within that margin, so in this case it is positioned off the right side of the screen.

[wiki page](https://github.com/TonicArtos/SuperSLiM/wiki/Content-View-Attributes-and-Parameters)

I should probably modify the example app to let the margin values be experimented with.

**Comment by AndroidDeveloperLB** [comment]
I see. Sorry for the false positive.
