### ISSUE TITLE
LayoutParams.layoutId confusing name.

### ISSUE THREAD

**Issue by PatrickDattilio** [TonicArtos/SuperSLiM#28]
Could we consider renaming layoutId? Perhaps to sectionId, section, or sectionManager? The value refers to the id/position of the section in the SectionLayoutManager. 
```java
final LayoutManager.LayoutParams lp = (LayoutManager.LayoutParams) holder.itemView.getLayoutParams();
lp.layoutId = 1;
```
```java
final LayoutManager.LayoutParams lp = (LayoutManager.LayoutParams) holder.itemView.getLayoutParams();
lp.section = 1;
lp.sectionId = 1;
lp.sectionManager = 1;
```
I think one of these is easier to understand/read.

**Comment by TonicArtos** [comment]
I also don't like the naming, and I've considered using 'kind' too.

I think 'lp.sectionManager' can work.

To me, the other two don't imply matching a registered id for a SLM, and instead suggest incrementing section numbers for each section.

**Comment by PatrickDattilio** [comment]
I agree, sectionManager seems to be the best fit!

**Comment by TonicArtos** [comment]
Agreed, change to sectionManager.
