### ISSUE TITLE
Nested Sticky Headers

### ISSUE THREAD

**Issue by PatrickDattilio** [TonicArtos/SuperSLiM#29]
Is it possible to have a second header stick below another header?

![Double Sticky](https://cloud.githubusercontent.com/assets/601185/6258489/e7262700-b796-11e4-9a07-cc46323335ea.gif)
)

I'd like the white sections (above each square image) to stick below the sticky navigation bar, and have the image scroll under. Is this currently possible?

**Comment by TonicArtos** [comment]
I'm guessing you mean to have content items be sticky too. I haven't explained it in the documentation yet, but headers are handled by the LayoutManager and content items by the SectionLayoutManagers (SLM). If you want to have content items be sticky, it would have to be added to a SectionLayoutManager implementation. I don't think this behaviour belongs in the default linear, grid, and staggered grid layout implementations, but feel free to write your own.

However, if you mean having subsections with sticky subheaders. It is intended to be possible to write a SLM which nests others. I actually have plans to do this for one of my projects.

**Comment by TonicArtos** [comment]
I see your .gif now. This could definitely be satisfied by either approach. I think I'll experiment with both ways myself and see how well the current design supports them. However, this will only happen after milestone 5 as I want to get the staggered grid layout done asap.

**Comment by PatrickDattilio** [comment]
I think having subsections/ nested sections would work perfectly for this. The navBar would be the section header.it would have a sub/nested sections, each with their own header and item.

**Comment by TonicArtos** [comment]
Okay, so this has gotten pulled into the next big version. The interface for declaring subsections is like this:
```java
class LayoutParams … {
…
    public void setSubsections(List<Integer> sectionFirstPositions);
…
}
```
This is a mirror of the same interface that is coming for top level section declaration, except this is on the configuring section item (first item in section) instead of in the adapter.

**Comment by TonicArtos** [comment]
Okay, this might be changing a little more. I am still investigating this but, it looks like I'll making section declaration a proper directed graph. This means sections and subsections will be declared up front. This will simplify some section management for me, but also allow sections that contain only subsections and no header, which was a sticking point with the previous design.

While LayoutManager will manage the section graph from then on, but it will still have to pull the full graph at times. So it is probably wise to keep the graph up to date with data set changes. 

The only difficulty really is adding and removing sections. These events are definitely associated with the notify actions, but I am not yet sure what will be a good interface to complement it.

**Comment by jjhesk** [comment]
+1

**Comment by TonicArtos** [comment]
After all this time. Almost done in version5. Tracked on #192.
