### ISSUE TITLE
 Fixed margins, Sticky headers, and Header position -> Inline causing scrolling bug

### ISSUE THREAD

**Issue by kplutchak** [TonicArtos/SuperSLiM#31]
When Fixed margins, Sticky headers, and Header position -> Inline options are selected in the example  code (and I'm assuming otherwise as well), the following unusual behavior occurs when scrolling down to where the second header should be visible.

![super_slim_bug](https://cloud.githubusercontent.com/assets/1146109/6261809/b90953b0-b7aa-11e4-8dfb-bfb9fcf9220c.gif)

**Comment by TonicArtos** [comment]
Fix going into v0.2.3.

**Comment by TonicArtos** [comment]
Argh, I screwed up branching the 0.2.x correctly.
