### ISSUE TITLE
Bug  when 'fling' scrolled to the recycler` top or bottom edge

### ISSUE THREAD

**Issue by simonwzb** [TonicArtos/SuperSLiM#35]
I test it both in the raw-sample-app and my app, the bug still exist.
I describe it as follows:
When 'flying' to the edge, the recylerview becomes imperfect.
If the Item` height is enough tall ,which lead to the 'flying' speed enough slow, the bug won`t occured.

Screen shots(initial, 'flying' to the top edge of the screen, flying agin):

![1](https://cloud.githubusercontent.com/assets/8718470/6280814/bc23ff88-b8ee-11e4-90a8-ef88f3848bf4.png)
![2](https://cloud.githubusercontent.com/assets/8718470/6280815/c0975c2c-b8ee-11e4-8bc2-39f2935c7c09.png)
![3](https://cloud.githubusercontent.com/assets/8718470/6280816/c707671e-b8ee-11e4-82f8-17ed3c0f6a8a.png)

Why it occured?

**Comment by TonicArtos** [comment]
Are you saying the bug only shows when item heights are small?

**Comment by TonicArtos** [comment]
Ah, I managed to recreate it. It does appear to be related to scrolling performance.

**Comment by simonwzb** [comment]
Yes you get it ~ 
Your answer is efficient , it is good expierence using your lib.
