### ISSUE TITLE
Gridlayout ignores margins

### ISSUE THREAD

**Issue by Eifelschaf** [TonicArtos/SuperSLiM#43]
Hi!

first of all: a nice library. A bit hard to setup, but the result is amazing!

I have a little issue: The GridSectionLayoutManager ignores the margin on my layouts.

I have some CardViews that use a layout_margin of 8dp in the topmost view. The default layoutmanagers in the RecyclerView support library recognize this margin and render the views accordingly. However your manager requires another view wrapped around it to make the margin visible.

**Comment by TonicArtos** [comment]
Thank you.

Plans are afoot to make setup easier, see #41, Also, there is a big update coming to improve performance and fix some major bugs in v0.3.0. 

As for the issue, yes margins are presently ignored, I haven't implemented support for it yet. I'll add it to my todo list.

**Comment by Eifelschaf** [comment]
Thanks for the quick response :)

I found the margin. It's at the right of the view, apparently, all collapsed. So the main view is rendered in the correct size, but the margin is ignored for the placement. I will just add some FrameLayout around my views to enable the margin.

**Comment by TonicArtos** [comment]
That should work around the issue for now.

**Comment by TonicArtos** [comment]
Oh, what did you find hard about the setup? I'd appreciate your input.

**Comment by Eifelschaf** [comment]
It's a bit hard to always add the first view in the section. having to setup teh viewholder like this looked a bit weird. It might perhaps be better to request the sections (including their position) once via a custom method in the adapter and store this information. I have an object structure that defines my list and I have to count the top level items for each subitem just to provide the proper number. This ias a bit anoying

**Comment by TonicArtos** [comment]
I understand what you mean, and I think the idea merits investigation. Just to clarify, with your idea, you would still package the section headers in the dataset?

**Comment by Eifelschaf** [comment]
Actually no, I would not package them then. Like this I could imagine something like this library does: https://github.com/eowise/recyclerview-stickyheaders there's an adapter for the headers and one for the items. If the item one returns the same ID as an already existing header it does not duplicate the header, otherwise it adds a new one. (unfortunately this library did not work well with grids as it uses the headers as decorations...)

**Comment by TonicArtos** [comment]
I don't think I will go away from packaging headers in the dataset. I think the RecyclerView design supports the idea that the adapters don't need to have a one-to-one mapping of data items to views. However I'll see what I can do to lighten this burden. Supplying section data in a second channel could be a good idea to do this.

**Comment by Eifelschaf** [comment]
Nice to hear :) I must say: your approach also has some advantages.

May I ask another question?

I have a LinearLayoutmanager for my headers and a grid manager for my items. I expected something like 

-------header------
-item- -item- -item-
-item-
-------header------

But I only get one column of items. Is this an issue with your 0.3 version or am i doing anything wrong? (I can post some code if you like)

**Comment by TonicArtos** [comment]
The header for each section should have the same layout set as the rest of the section items.

**Comment by TonicArtos** [comment]
The issue with v0.3 is that I took out the overscroll correction, which was buggy, but without it things are also bugged. I am working on fixing the root cause at the moment.

**Comment by Eifelschaf** [comment]
Ahhhhhhhh so i WAS wrong about this :) Thanks for the clarification!
