### ISSUE TITLE
The Layoutmanager ignores visibility attributes

### ISSUE THREAD

**Issue by Eifelschaf** [TonicArtos/SuperSLiM#45]
Hi again,

apparently the layoutmanager ignored the visibility attribute of the views. I have a solution in place that switches the headers to invisible if they are empty (but they start a new section nevertheless).

Unfortunately I have to set the height to 0 in the layout params ot make it work as expected. Perhaps consider implementing this in one of the next releases.

**Comment by TonicArtos** [comment]
Yes, this is something I haven't looked into. With the exception of actually supporting this, the only real issue I see is GONE status in the grid layout. At present the item position is used to place views into the correct column, for this GONE would functional nearly identical to INVISIBLE.

**Comment by Eifelschaf** [comment]
Indeed you might have to have a virtual index of the view that is not incremented if a view is gone instead of invisible. 

Or you might do the following:
If it's a header it's counted as a view, but not rendered
if it's a normal view it's ignored and the layout manager continues with the next item.

**Comment by TonicArtos** [comment]
Basically, it would make positioning in the grid layout far more complex if you want to avoid scanning back to the beginning of the section every time you want to start positioning views. Anyway, I will get in support for visibility status eventually, though it might come in stages.

Thank you for reporting the issue :)

**Comment by Eifelschaf** [comment]
Perhaps have a look at what google does in their implementation. The source of the layoutmanagers should be public.

**Comment by TonicArtos** [comment]
You'll be happy to know that View.GONE is not honoured for Google's implementations either.

In v0.4.0, SuperSLiM has the same view visibility behaviour. View.VISIBLE and View.INVISIBLE are adhered to, GONE is ignored.
