### ISSUE TITLE
View "jumping" on scroll when not enough items to fill screen

### ISSUE THREAD

**Issue by MatFl** [TonicArtos/SuperSLiM#47]
When there are only a few items, so the view only fills part of the screen, and I try to scroll, the whole view jumps to the bottom of the screen (and back to the top if I scroll in the other direction).

To reproduce just remove most of the countries from the example app, so the view does not fill the screen. Then try to scroll up and down.

**Comment by TonicArtos** [comment]
Thank you for your bug report. I'll get this fixed asap.

**Comment by TonicArtos** [comment]
Out in v0.4.2. You should be able to grab it now, though it isn't indexed yet on the website.

**Comment by MatFl** [comment]
Awesome. Thanks for the fast fix!

**Comment by TonicArtos** [comment]
Actually, it looks like I was premature. This has highlighted another new bug.

**Comment by TonicArtos** [comment]
Okay, the related issue is fixed, and released, in v0.4.3.
