### ISSUE TITLE
Headers are displayed underneath the regular cards

### ISSUE THREAD

**Issue by Eifelschaf** [TonicArtos/SuperSLiM#48]
Hi again!

I found another issue: Sticky headers are somehow displayed below my cards. this may have something to do with the elevation level of a card on Android 5, but I am really not sure.. Could you have a look at it and make sure that headers are always on top? (telling me what may be wrong is also an option ;) )
![screenshot_2015-03-03-09-26-23](https://cloud.githubusercontent.com/assets/1673940/6458818/1af1b658-c188-11e4-940f-87501a879d30.png)

**Comment by TonicArtos** [comment]
Please tell me which version of SuperSLiM you are using. Thanks.

**Comment by Eifelschaf** [comment]
0.4.1

**Comment by TonicArtos** [comment]
Okay thanks, I was hoping it was margins related. I wonder if it is caused by the child index ordering? I don't know much about how Android 5 does its elevation trick.

**Comment by Eifelschaf** [comment]
I guess it's because the cards get an elevation property which makes them display with a shadow... I was hoping this did not affect the headers, but apparently I have to solve this myself then (as it's not necessarily related to your framework).

**Comment by TonicArtos** [comment]
Well, it looks like the cards are intruding on the headers layout. I thought the cards should have margins to prevent that. I am going to take a look at it, but as far as I am aware, I've done everything I should to properly measure and layout views.

**Comment by Eifelschaf** [comment]
Indeed, the layout is perfectly fine, but the sticky headers slip under the cards while scrolling.

**Comment by TonicArtos** [comment]
Oh, I understand now. Things are fine until the headers are in their stickied state. This makes perfect sense since elevation in android 5 changes the drawing order.

I don't see why SuperSLiM shouldn't be able to handle this. What do you think of these ideas.

1) You can set a listener for when headers are stickied. This would give you the view and perform operations on it.

2) SuperSLiM offers configuration options to automatically adjust a headers elevation for the stickied state.

**Comment by Eifelschaf** [comment]
The second one sounds perfect, but the first will also allow some workarounds. Although I guess I am getting a shadow if the elevation is changed, so changing the drawing order may be more reasonable. I can't imagine any reason why a sticky header should not always be on top.

**Comment by TonicArtos** [comment]
I am not sure I can override the drawing order. Also, in my understanding of the material design spec, the headers should probably get elevation and shadow if content is to pass underneath. 

You can disable the shadows using setOutlineProvider(null) on the header views. Maybe this could also be done automatically per the LayoutManager configuration.

**Comment by Eifelschaf** [comment]
Hm.. sounds good, I will give it a try.

**Comment by TonicArtos** [comment]
Cool, tell me how it goes.

**Comment by TonicArtos** [comment]
Here is a detailed look at the solution.

https://github.com/TonicArtos/SuperSLiM/wiki/Sticky-elevation-proposal

**Comment by Eifelschaf** [comment]
My first results: setting an elevation works perfectly fine. A card has a default elevation of 2dp (which is the minimum value for the header then).

If I set teh outline provider to null I get no shadow. I think you don't really have to take a specific action for this, just leave this post as a documentation and link to it.

**Comment by TonicArtos** [comment]
Thank you.
