### ISSUE TITLE
ItemDecorator  找不到？

### ISSUE THREAD

**Issue by sunshangfeng** [TonicArtos/SuperSLiM#54]
你好我刚学习 使用  android studio    
 您的 包 我是这样导入 的     compile 'com.tonicartos:superslim:0.4.+'
  可是 找不到 ItemDecorator   这个类   

LinearSLM   GridSLM   这两个缺可以导入  我导入错误了吗？？

**Comment by TonicArtos** [comment]
Hi there, ItemDecorator is only available in the snapshot for development on version 0.5.

The snapshot is updated from time to time, and there are no guarantees of a stable interface. As such, your code may unexpectedly fail to compile.

---

To get the snapshot:

```groovy
repositories {
    maven { url "https://oss.sonatype.org/content/repositories/snapshots/" }
}
```

```groovy
dependencies {
    compile 'com.tonicartos:superslim:0.5.0-SNAPSHOT'
}﻿
```

**Comment by sunshangfeng** [comment]
非常感谢

**Comment by TonicArtos** [comment]
You are welcome.
