### ISSUE TITLE
TextView measurement error after rebinding ViewHolder.

### ISSUE THREAD

**Issue by TonicArtos** [TonicArtos/SuperSLiM#56]
Sometimes view measurement doesn't update.

bugged measurement

```
               Fetched  D  position 82
                        D  82 was cached true
                        D  height 161
           measurement  D  params height -2
                        D  height 161
```

Correct measurement

```
               Fetched  D  position 82
                        D  82 was cached true
                        D  height 161
           measurement  D  params height -2
                        D  height 218
```

Maybe related to #55.

---

Further investigation reveals sometimes the views are just not being measured, though the call through recycler view is being made. There must be some residual state stopping measurement. What can stop measurement?

**Comment by TonicArtos** [comment]
Okay, so this is a problem caused by internal measurement logic in TextView. TextView will not measure itself again if it believes there has been no change to its content. The workaround to force TextView to measure itself again is for SuperSLiM to set new layout dimensions before measuring again.

**Comment by TonicArtos** [comment]
One solution is to not use the match_parent value for layout_width for TextViews that are in a view group.

**Comment by TonicArtos** [comment]
Another is to use different viewTypeIds for views intended for different layouts.

**Comment by TonicArtos** [comment]
So far I have been unable to work around the problem from the SuperSLiM end of things. :(

**Comment by TonicArtos** [comment]
Closing for now, people can resurrect this if they want to look into it again.

**Comment by PatrickDattilio** [comment]
Maybe leave this open so people can see/contribute, or make a note of it in the docs?

**Comment by TonicArtos** [comment]
I was going to note it in the docs, but sure, I'll leave it open too.

**Comment by bejibx** [comment]
Maybe report this as an issue to AOSP issue tracker?

**Comment by TonicArtos** [comment]
I don't think it is a bug. I mean, TextView and RecyclerView are both doing the correct thing. For now, I don't plan on doing anything about this, but in the future I might see if there is something I can do; patching RecyclerView, or perhaps some kind of change to SuperSLiM.
