### ISSUE TITLE
Performance is all over the place with EditText

### ISSUE THREAD

**Issue by TonicArtos** [TonicArtos/SuperSLiM#58]
Scrolling quickly with lots of edit text views is poor. This is probably caused by having to measure a header offset for side aligned headers.

**Comment by AndroidDeveloperLB** [comment]
I've noticed bad performance of scrolling for this layout (shortened to keep it easy to read) : 

    <horizontal LinearLayout>
      <FrameLayout with 2 identically sized views inside/>
        <vertical LinearLayout>
          <TextView/>
          <horizontal LinearLayout with 5 imageViews/>
        </vertical LinearLayout>
    </horizontal LinearLayout>
