### ISSUE TITLE
StickyHeader never unsticks.

### ISSUE THREAD

**Issue by PatrickDattilio** [TonicArtos/SuperSLiM#60]
While attempting to upgrade to 0.4.5, it seems that once my StickyHeader navbar sticks to the top, it never allows itself to be pulled back down, and expose the data above. It's too sticky!

[Example code here](https://github.com/PatrickDattilio/SuperSLiMExample)

**Comment by TonicArtos** [comment]
Sorry, can you please remind me which version you were on before?

**Comment by PatrickDattilio** [comment]
v0.2.4

**Comment by TonicArtos** [comment]
Thanks, I'll look into it.

**Comment by TonicArtos** [comment]
Sorry, I was a bit caught up with some other things. I just took a look at this, it looks like the bug was introduced back in v0.4.0. I'll get this fixed shortly.

**Comment by TonicArtos** [comment]
Fixed in version v0.4.6.
