### ISSUE TITLE
Building example: several attributes in layout/header_item.xml are not found in attrs.xml

### ISSUE THREAD

**Issue by danielfaust** [TonicArtos/SuperSLiM#63]
header_item.xml uses 'slm_isHeader' which is not found in attrs.xml
header_item.xml uses 'slm_section_headerMarginStart' which is not found in attrs.xml

**Comment by TonicArtos** [comment]
Thank you for your bug report.

I know it is broken. Your report is also just the tip of the iceberg. Anyway, this has happened because example hasn't been updated for the changes in the last merge. Sorry, I shouldn't have uploaded code I knew to be broken to master.

**Comment by TonicArtos** [comment]
Unless you are trying to see what is happening on tip, I recommend checking out the branch `early_release_4`. It is the current stable branch.

**Comment by TonicArtos** [comment]
In light of this issue, I have made the current stable branch the default branch. This should prevent this from happening again. Sorry about that.

**Comment by danielfaust** [comment]
Hi, thanks for the effort. I had to move fast so then I chose TwoWayView, which turned out suit my needs (Staggered Grid). I'm sorry I just dumped the issue here without really checking out the source code. I figured that the Sample was not in sync with the code. Also sorry for not helping out but just pointing out what's wrong without fixing it. :(

**Comment by TonicArtos** [comment]
Two way view is good too. :)
