### ISSUE TITLE
Import class

### ISSUE THREAD

**Issue by wangjinyu501** [TonicArtos/SuperSLiM#64]
compile 'com.tonicartos:superslim:+'     using in this way,i can't import some classes.Why?

**Comment by TonicArtos** [comment]
Please check that you are not importing the 0.5 snapshot.

**Comment by wangjinyu501** [comment]
Okey,your work is nice.I hope you can add the fast scroll as soon as possible,it's really a big improvement.

**Comment by TonicArtos** [comment]
Thanks. I hope to add fast scroll soon.
