### ISSUE TITLE
Scroll issue with small number of sections/items.

### ISSUE THREAD

**Issue by PatrickDattilio** [TonicArtos/SuperSLiM#67]
I'm running into an issue when touching the screen in a partially empty recyclerview:
![scrollingbug](https://cloud.githubusercontent.com/assets/601185/6921826/1f307b64-d795-11e4-85c8-726d052044ea.gif)

Scrolling works fine when we have at least one more item. I would guess it's related to the navbar stickyheader section having no children?

Updated the example can be found here:
https://github.com/PatrickDattilio/SuperSLiMExample

**Comment by TonicArtos** [comment]
Thanks, I'll look into this asap.

**Comment by TonicArtos** [comment]
Hooray, I found some more time this evening to work on this. It turns out this only happens when there are no content items after the last header. It looks pretty simple to solve, so I imagine I'll have a fix out for it after dinner... and I have to add yet another test for version 0.5.

**Comment by PatrickDattilio** [comment]
Thanks for the quick turnaround!
