### ISSUE TITLE
custom group like contact list

### ISSUE THREAD

**Issue by jjhesk** [TonicArtos/SuperSLiM#68]
Are there any API method that i will able to put characters into the group? For example, I am looking to group [0-9] and [~!@#$%^&*()_+] and some custom conditions into one group called # and with the letter I want it to make it to group it like A for Aa, B for Bb and C for Cc and so forth.

**Comment by TonicArtos** [comment]
From your question, I understand that you may be looking at the example, how it takes a list and processes it into sections and creates headers. Despite the example, SuperSLiM is not concerned with how you implement your adapter or section your content.

**Comment by jjhesk** [comment]
Are there any sample that I could implement the a basic section to my content? I am still confuse about the mechanism of sectioning..

**Comment by TonicArtos** [comment]
No, SuperSLiM will not help you with adapter implementation. Implementing the adapter is easy anyway, you just need to implement a virtual or real list of items grouped into sections. After all, an adapter for SuperSLiM is little different from a normal one for any other RecyclerView LayoutManager. 

The issue you linked is a discussion about moving section data out of the item layout parameters into some other communication mechanism. It has little to do with the fundamental architecture of an adapter. 

If you have trouble sorting a list or writing lookup tables for a virtual list, then I can't really help you anyway, such tasks are the fundamental basics first taught to any programmer.
