### ISSUE TITLE
onBindViewHolder called if a overlaying view was changed.

### ISSUE THREAD

**Issue by binloan** [TonicArtos/SuperSLiM#69]
In the shown Activity I have a textView above the RecyclerView. A Timertask is updating the TextView every second. 

Once the TextView is updated, the underlaying RecyclerView Item is redrawn. This causes ugly effects when using animations like in the video shown below. Also because the onBind method is recalled all processes are done again. (In this case a AsyncTask which loads the images). This heavily influences performance.

Video: https://drive.google.com/file/d/0B-WlKDlvNCO5RUJEQkd3M3BncXM/view?usp=sharing

**Comment by TonicArtos** [comment]
At the moment the layout doesn't do any caching, and assumes layout calls means a complete state refresh is needed. I'll make sure to investigate this on the development version.

**Comment by TonicArtos** [comment]
I don't see this behaviour on my end. Could you please elaborate on how you are overlaying your text view? What kind of container are you using? It is possible that the text view is causing a change in dimensions that requires the RecyclerView to do a new layout pass, this would cause your observed behaviour.

**Comment by binloan** [comment]
Indeed I think this was my error. I changed my TextView to a button that has a fixed height fills the full width. The error didn't appear after this anymore. Still the other error I sent you via eMail is still a problem. If you need additional information there I will be glad to help!
