### ISSUE TITLE
Will minSdk 9 work?

### ISSUE THREAD

**Issue by ThanosFisherman** [TonicArtos/SuperSLiM#72]
I have a question. Can I use this library on minSdkVersion 9? If not do you know any other alternatives that use sticky headers with RecyclerView? thanks

**Comment by Gordey** [comment]
I use tools:overrideLibrary="com.tonicartos.superslim" in <use-sdk>. On sdk 10 work fine.

**Comment by ThanosFisherman** [comment]
Sounds kind of hacky but I'm gonna try it hopping it won't cause any problems on gingerbread

**Comment by TonicArtos** [comment]
I'll change the library support configuration for you, but add documentation to note it isn't tested on versions before android 4.

**Comment by ThanosFisherman** [comment]
Cool, thanks Tonic, I'll post back if I face any issues on gingerbread devices

**Comment by ThanosFisherman** [comment]
btw running the example on android 2.3.7 does a lot of weird things, Rendering is not good and sometimes crashes. :(

**Comment by TonicArtos** [comment]
Interesting, I didn't encounter any problems on the x86 emulator version.

**Comment by ThanosFisherman** [comment]
I tested this on Gennymotion android 2.3.7 You can try it. I will also test this on a physical 2.3.7 device soon

**Comment by ThanosFisherman** [comment]
Just tested this on my motorola defy+ android 2.3.7 and works great. So I don't know what's wrong with genymotion emulator

**Comment by TonicArtos** [comment]
I'm sorry that the emulator doesn't work properly with it. It seems to work fine on the official ones.
