### ISSUE TITLE
Item views without layout parameters cause NPE

### ISSUE THREAD

**Issue by TonicArtos** [TonicArtos/SuperSLiM#74]
Problem initially reported in thread for #4.

Caused by view inflation like:

```java
View.inflate(mContext, R.layout.item_country_content, null);
```

**Comment by jesielin** [comment]
i think this is the android's bug,there is something different between the several inflate method about the view width measuring time,now i have no time to check detail difference,i will check it later and thank you for concern about my problem~

**Comment by TonicArtos** [comment]
Well, in this case, RecyclerView should call generateLayoutParams() on LayoutManager.
