### ISSUE TITLE
Example crashes when using AppCompat 22.1.0 

### ISSUE THREAD

**Issue by Iketaki** [TonicArtos/SuperSLiM#76]
I tried to run the example project but it crashed.
Stacktrace is below.

```
FATAL EXCEPTION: main
                        E  Process: com.tonicartos.superslim.example, PID: 1250
                        E  java.lang.RuntimeException: Unable to start activity ComponentInfo{com.tonicartos.superslim.example/com.tonicartos.superslimexample
                           .MainActivity}: java.lang.IllegalArgumentException: AppCompat does not support the current theme features
                        E      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2184)
                        E      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2233)
                        E      at android.app.ActivityThread.access$800(ActivityThread.java:135)
                        E      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1196)
                        E      at android.os.Handler.dispatchMessage(Handler.java:102)
                        E      at android.os.Looper.loop(Looper.java:136)
                        E      at android.app.ActivityThread.main(ActivityThread.java:5001)
                        E      at java.lang.reflect.Method.invokeNative(Native Method)
                        E      at java.lang.reflect.Method.invoke(Method.java:515)
                        E      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
                        E      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
                        E      at dalvik.system.NativeStart.main(Native Method)
                        E  Caused by: java.lang.IllegalArgumentException: AppCompat does not support the current theme features
                        E      at android.support.v7.app.AppCompatDelegateImplV7.ensureSubDecor(AppCompatDelegateImplV7.java:360)
                        E      at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:246)
                        E      at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:106)
                        E      at com.tonicartos.superslimexample.MainActivity.onCreate(MainActivity.java:115)
                        E      at android.app.Activity.performCreate(Activity.java:5231)
                        E      at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
                        E      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2148)
                        E      ... 11 more
```

**Comment by ThanosFisherman** [comment]
Yes, you just need to change your values > styles.xml from 
`<item name="android:windowNoTitle">true</item>`
to
`<item name="windowNoTitle">true</item>`

**Comment by Iketaki** [comment]
It works. Thank you.
I hope this will be fixed in next version:)

**Comment by TonicArtos** [comment]
I probably should update the example project. I am going to reopen this until then.

**Comment by jesielin** [comment]
Error:A problem occurred configuring project ':app'.
> Could not resolve all dependencies for configuration ':app:_debugCompile'.
   > Could not find com.android.support:recyclerview-v7:22.1.1.
     Searched in the following locations:
         https://jcenter.bintray.com/com/android/support/recyclerview-v7/22.1.1/recyclerview-v7-22.1.1.pom
         https://jcenter.bintray.com/com/android/support/recyclerview-v7/22.1.1/recyclerview-v7-22.1.1.jar
         https://repo1.maven.org/maven2/com/android/support/recyclerview-v7/22.1.1/recyclerview-v7-22.1.1.pom
         https://repo1.maven.org/maven2/com/android/support/recyclerview-v7/22.1.1/recyclerview-v7-22.1.1.jar
         file:/Users/shawn/Documents/android-sdk/extras/android/m2repository/com/android/support/recyclerview-v7/22.1.1/recyclerview-v7-22.1.1.pom
         file:/Users/shawn/Documents/android-sdk/extras/android/m2repository/com/android/support/recyclerview-v7/22.1.1/recyclerview-v7-22.1.1.jar
         file:/Users/shawn/Documents/android-sdk/extras/google/m2repository/com/android/support/recyclerview-v7/22.1.1/recyclerview-v7-22.1.1.pom
         file:/Users/shawn/Documents/android-sdk/extras/google/m2repository/com/android/support/recyclerview-v7/22.1.1/recyclerview-v7-22.1.1.jar
     Required by:
         cwapp:app:unspecified > com.tonicartos:superslim:0.4.12

**Comment by TonicArtos** [comment]
The Support Library v22.1.1 is available as an update through the Adnroid SDK Manager.
