### ISSUE TITLE
Header with no content will Scroll with blank space

### ISSUE THREAD

**Issue by kingargyle** [TonicArtos/SuperSLiM#83]
This is a bit hard to describe so let me setup some situations.

header
  content
  content
empty section header
header
   content
   content

Scroll up the list until the last header is the sticky header and the Empty section header is off the screen.  Then start to scroll down, the empty section header will continue to be sticky and the screen starts to fill with blank white space, keep scrolling and eventually the content for the first header will start to appear, once this happens the view adjusts and the screen scrolls as normal.

I was able to get into this situation as we have an Expandable Grid View, in which you click on section headers to expand and collapse the section content for that header.  SLiM has been a nice drop in replacement, everything else I've been able to work around, but this scrolling is something that seems a SLiM issue for the Grid layout manager.

**Comment by TonicArtos** [comment]
I remember fixing a problem like this in the past. It is possible I missed it on GridSLM.

**Comment by kingargyle** [comment]
It is similar to issue #70 in which the content is removed from the end of the list.  This particular bug the content is either removed from the middle of a list, or there is no content to begin with.

**Comment by TonicArtos** [comment]
At first I misunderstood which scrolling direction you meant. I see that this is an error when you try to scroll past a header towards the content start. The bug manifests in two ways. The way you described with a sticky header, and with the header vanishing if it isn't sticky.

I'll get this fixed.

**Comment by kingargyle** [comment]
Thanks. I'll check it out when I'm at work tomorrow.

**Comment by kingargyle** [comment]
Verified that this fix the issue.  Thanks again for the quick turn around.
