### ISSUE TITLE
Need good examples for v0.5

### ISSUE THREAD

**Issue by TonicArtos** [TonicArtos/SuperSLiM#84]
This is a list of examples and walk-throughs to make.
#### Basic usage

An example app which demonstrates the following:
- [ ] A ListView style interface using LinearSLM.
- [ ] A GridView style interface using GridSLM.
- [ ] Creating a section graph.
- [ ] Adding headers to sections.
- [ ] Enhancing with ItemDecorators.

Each sub-example is wholly contained in its own package inside the app. A simple UI allows the user to navigate the examples and provides a link to a wiki walk-through for each one.
#### Interactive data example

An example which allows the user to create, edit, and remove data in a database. 
- [ ] yup.

This is primarily a demonstration on how to keep the section graph up to date when making data change notifications. It will also serve as an example on one way to map data in a database to the section graph.

**Comment by ThanosFisherman** [comment]
It would be nice if there was an example that uses a good practice of how to handle itemClicks on both Headers and simple items. Maybe show a toast message on each item/header click respectively. It doesn't have to be a seperate example, it can be implemented on ListView/GridView examples
