### ISSUE TITLE
findFirstCompletelyVisibleItemPosition and findLastCompletelyVisibleItemPosition don't find anything.

### ISSUE THREAD

**Issue by kingargyle** [TonicArtos/SuperSLiM#88]
The following stack trace occurs if I try to use the layoutManagers.findFirstCompletelyVisibleItemPosition to obtain the position of the first item on the screen.

   java.lang.NullPointerException: Attempt to invoke virtual method 'android.view.ViewGroup$LayoutParams android.view.View.getLayoutParams()' on a null object reference
            at android.support.v7.widget.RecyclerView$LayoutManager.getPosition(RecyclerView.java:5017)
            at com.tonicartos.superslim.LayoutManager.findFirstCompletelyVisibleItemPosition(LayoutManager.java:139)

I do not get a NPE if I switch the call to layoutManager.findFirstVisibleItemPosition().

I can use the later as a work around to obtain the position, but the former is preferable.

This is with version 4.12 of SuperSLiM.

**Comment by TonicArtos** [comment]
Sorry, this weekend I've noticed there are bugs with both completely visible methods. I just haven't fixed them and should've posted issues already. It is obvious that I've been struggling keeping everything tested so at the moment I am working on getting some automated tests so I'll catch these issues more often in the future.

**Comment by kingargyle** [comment]
Have you looked into using Robolectric to provide some unit testing around everything?

**Comment by TonicArtos** [comment]
It is one of the options I have been reading about today.

**Comment by TonicArtos** [comment]
I've only ever used the stock unit tests before, so I've been woefully neglecting this aspect :(

**Comment by kingargyle** [comment]
Robolectric is what I recommend.  We use it extensively at work, that combined with Mockito, and Dagger make for a nice testing framework.

**Comment by TonicArtos** [comment]
Thanks. I guess I'll be busy learning new things for a while.

Also, I am adding debug logging to the library. Though I need to figure out how to host the debug variant, I think I can do it as version = 4.12-debug. I am hoping, once that is done, we'll all find it easy to diagnose whether layout issues are bugs in the library or not.

**Comment by TonicArtos** [comment]
@kingargyle Thank you for your recommendations. Robolectric and Mockito are working pretty well, but I feel that testing RecyclerView LayoutManagers isn't the easiest of things.

**Comment by kingargyle** [comment]
With Mockito if you can Spy on a real object, you can tell it not do things, or to always return certain things.   Look into spying on real objects, then you can setup mockito so it handles the results of protected methods that you may call that are extended or inherrited from Recycler View itself, that way you aren't testing Recycler View, but just your extensions and implementations.

**Comment by TonicArtos** [comment]
Partial mocks and reflection is how I've started writing some of the unit tests on the internal library methods. I am also starting to understand the utility of Dagger for testing, not that I am yet using it.

**Comment by TonicArtos** [comment]
Hmm, I was just looking at these methods. I've completely rewritten this part on the development branch :(. This happened because LayoutManager no longer knows about headers, that logic is now in the abstract SectionLayoutManager class.

**Comment by TonicArtos** [comment]
Are there no views completely on the screen when this NPE happens?

**Comment by TonicArtos** [comment]
Never mind.

**Comment by tushar-nallan** [comment]
@TonicArtos I'm facing the same crash, but in a completely vanilla RecyclerView implementation and was hoping you could help me out. Can you tell me what causes the crash in the first place?
