### ISSUE TITLE
Cant import

### ISSUE THREAD

**Issue by faizandedia** [TonicArtos/SuperSLiM#90]
trying to import, doesn't work with dependency, any help?

dependencies {
    compile 'com.tonicartos:superslim:0.4.12'
}

**Comment by TonicArtos** [comment]
Check that you have either the maven central or jcenter repositories enabled in your top level build.gradle file.

**Comment by TonicArtos** [comment]
@faizandedia Do you still have the problem?

**Comment by TonicArtos** [comment]
Closing until further information is received.
