### ISSUE TITLE
notifyDataSetChanged slight scroll after fixing #70

### ISSUE THREAD

**Issue by cyberphere** [TonicArtos/SuperSLiM#91]
After fixing overscroll correction in #70 you've created another one. When notifyDataSetChanged, or any other notify, is called recyclerView gets scrolled up. It worked fine before version 0.4.10.
This happens when I add new items to adapter and call notifyDataSetChanged, or when I call notifyItemChanged.

**Comment by TonicArtos** [comment]
Is this a scroll, or is it an overscroll? If it is just a scroll to a different position because the numbers changed in the adapter, it is something I am fixing in 0.5.

**Comment by ThanosFisherman** [comment]
Hey Tonic, I'm not sure  what you mean by overscroll but I believe this is just a simple scroll issue. It just scrolls a little bit by itself (you can still see the first item tho) even on first adapter asignment.

**Comment by TonicArtos** [comment]
Overscroll is when the content is not positioned correctly after the normal layout pass. It is caused when the content position and the virtual display area gets out of sync, like on a screen rotation or data change. The term comes from the support lib source.

Anyway, I'll look into this issue soon.

**Comment by cyberphere** [comment]
That's right, just scrolls a little bit every time.
