### ISSUE TITLE
canScrollVertically returns false sometimes incorrectly

### ISSUE THREAD

**Issue by woxblom** [TonicArtos/SuperSLiM#94]
Im using a refresh layout and sometimes when I call canScrollVertically(-1) on the recyclerview used with the superslim layout manager it returns false even if I have not scrolled to the top. This results in the refresh indicatior being shown to early.

It never happens if I fling the list to the top. Only if I drag slowly down.
I use version 4.13

**Comment by TonicArtos** [comment]
This issue may be the same as #97. It is possibly caused by incorrect handling of stickied headers.
