### ISSUE TITLE
Change from LinearSLM to GridSLM

### ISSUE THREAD

**Issue by andersonacs** [TonicArtos/SuperSLiM#96]
I'm using 0.4.13 version and should like in runtime change from LinearSLM to GridSLM. The following code is deprecated:

`
GridSLM.LayoutParams params = new GridSLM.LayoutParams(view.getLayoutParams());
params.setNumColumns(5);
view.setLayoutParams(params);`

how should I do it now?

**Comment by andersonacs** [comment]
Sorry for this issue I saw that you updated the example code to use this way:

`final GridSLM.LayoutParams lp = GridSLM.LayoutParams.from(itemView.getLayoutParams());`

**Comment by TonicArtos** [comment]
Sorry, I should have been more detailed in my release notes, and added an explanation in the Java doc.

**Comment by andersonacs** [comment]
Thanks for this great library. I take the opportunity to say that I would like much of contribute someway. I have written a example code and also i will help answer questions at the stackoverflow.
