### ISSUE TITLE
SwipeRefreshLayout not fully compatible with SuperSLiM

### ISSUE THREAD

**Issue by ThanosFisherman** [TonicArtos/SuperSLiM#97]
I'm facing the issue described [here](https://code.google.com/p/android/issues/detail?id=78191) 
SwipeRefreshLayout triggers the refresh behavior too early before the list is fully scrolled up to the top.
On the android issue tracker they say they have fixed it but it is still happening to me. Do you think it's library's fault?

**Comment by ThanosFisherman** [comment]
Hm this problem only occurs when using sticky headers. and with the latest version of superslim the `LayoutManager.LayoutParams.HEADER_STICKY` is deprecated. But I really want sticky headers what should I use instead??

**Comment by TonicArtos** [comment]
The sticky header setting is becoming default for all headers, and only
optionally off for inline headers.

**Comment by ThanosFisherman** [comment]
Ah good. So if I want it to be inline AND sticky what should I declare in the parameters? nothing?

**Comment by TonicArtos** [comment]
You should see this message explaining the deprecation.

So no real change for the current version. With regards to the library problem with SwipeRefreshLayout, it is likely that the stickied header is being detected and therefore it thinks the top of the content has been reached. TBH, I haven't looked into it yet. I'll get around to it, but I have more pressing things to do right now.

```java 
        /**
         * This constant has been marked as deprecated to indicate its pending replacement in the
         * next major version. In the future, sticky behaviour will be standard, and there will be
         * an option disable it with a new NONSTICKY constant, however, use of it will force the
         * INLINE display method.
         */
        @Deprecated
        public static final int HEADER_STICKY = 0x10;
```

**Comment by TonicArtos** [comment]
Oh, and there is an issue tracking the changes to the header settings, #89.

**Comment by ThanosFisherman** [comment]
Thanks for the heads up. I haven't attached the sources so I didn't see this message. (I just use the library via gradle dependency so I see no sources or docs) 

Yeah I believe that's the case with sticky header and SwipeRefreshLayout. Take your time. I'll check the source and make an attempt to fix it myself. But I'm kinda noob at such things :P

**Comment by TonicArtos** [comment]
Hmm, I thought the documentation came through with the gradle dependency.
I'll have to check that again.

**Comment by hzsweers** [comment]
For AARs, documentation and sources don't come through. You have to use something like this: https://github.com/xujiaao/AARLinkSources

**Comment by dvdciri** [comment]
@TonicArtos Why is this closed? I'm having the same issue and it appears to be related to the sticky headers. By removing the library it works fine, do we have a solution for this?
