### ISSUE TITLE
[Documentation] Transition from StickyHeaderView to SuperSLiM

### ISSUE THREAD

**Issue by ghost** [TonicArtos/SuperSLiM#98]
Hi Tonic,

I'm a big user of Sticky Header View, very used to its API, but when I look at the doc of SuperSLiM I am completely lost for the transition. Seems like many many things have changed.

As you own both libraries, it would be truly amazing to have a guide that explain how to transition a StickyHeaderView to SuperSLiM. 

Let me know your thoughts,
Stephane

**Comment by TonicArtos** [comment]
I am in the middle of transitioning SuperSLiM to a clearer API for the next version. When that is done I'll be documenting it in the wiki, and I think it should be more intuitive to users of the old style list view sticky headers API.

The pending changes have been discussed in a number of issues and on the wiki there is one document detailing some of the planned changes.
